const {test}=require('node:test');const assert=require('node:assert/strict');
const {Game}=require('../.test-output/Game.js');const A=require('../.test-output/Amount.js');const {translations,t}=require('../.test-output/I18n.js');
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),data};};
const game=()=>new Game(undefined,()=>2000000000000);
test('large amounts stay finite above native numeric range',()=>{assert.equal(A.add(10000,10000),10000+Math.log10(2));assert.equal(A.sub(10000,10000),A.ZERO);assert.equal(A.fmt(10000),'1.00e10000');assert.ok(Number.isFinite(A.sub(10000,9999)));});
test('normal kills open boss, boss kill advances stage',()=>{const g=game();for(let i=0;i<5;i++)g.damage(100);assert.equal(g.s.run.boss,true);assert.equal(g.s.run.stage,1);g.damage(100);assert.equal(g.s.run.stage,2);assert.equal(g.s.run.boss,false);});
test('failed boss returns to farm and permits manual retry',()=>{const g=game();g.s.run.kills=5;g.toggleBoss();g.s.run.bossLeft=.1;g.tick(.2);assert.equal(g.s.run.boss,false);assert.equal(g.s.run.bossFailed,true);g.damage(100);assert.equal(g.s.run.boss,false);g.toggleBoss();assert.equal(g.s.run.boss,true);assert.equal(g.s.run.bossLeft,30);});
test('max buy never overspends and locks gate heroes',()=>{const g=game();g.s.run.gold=A.amount(1000);assert.equal(g.buy(3,1),false);assert.equal(g.buy(-1,-1),true);assert.ok(g.s.run.gold<g.upgradeCost(-1));assert.ok(Number.isFinite(g.s.run.gold));});
test('prestige preserves permanent growth and resets the current run exactly once',()=>{const g=game();g.s.run.stage=g.s.maxStage=100;g.s.run.master=350;g.s.run.heroes[0]=50;g.s.pets[2]=10;g.s.artifacts[3]=5;g.s.skills[0]=3;g.s.run.spells[1]=20;g.s.run.mana=0;assert.equal(g.prestige('p1'),true);assert.equal(g.s.run.master,1);assert.equal(g.s.run.heroes[0],0);assert.equal(g.s.run.spells[1],0);assert.equal(g.s.run.mana,120);assert.equal(g.s.pets[2],10);assert.equal(g.s.artifacts[3],5);assert.equal(g.s.skills[0],3);const snapshot=JSON.stringify(g.s);assert.equal(g.prestige('p1'),false);assert.equal(JSON.stringify(g.s),snapshot);});
test('craft creates missing set pieces and preserves history after sale',()=>{const g=game();g.s.shards=100;for(let i=0;i<5;i++)assert.ok(g.craft('c'+i));assert.equal(new Set(g.s.equipment.map(e=>e.slot)).size,5);assert.equal(g.s.shards,65);g.equip(1);assert.equal(g.sell([1],'sell-equipped'),false);g.lock(2);assert.equal(g.sell([2],'sell-locked'),false);assert.ok(g.sell([3],'sell'));assert.equal(g.s.setHistory.length,5);assert.equal(g.s.equipment.length,4);});
test('failed transactions restore currency and RNG',()=>{const g=game();g.s.shards=0;const before=JSON.stringify(g.s);assert.equal(g.craft('bad'),false);assert.equal(JSON.stringify(g.s),before);});
test('persistent write failures roll back permanent spend',()=>{const store=memory(),g=new Game(store);g.s.shards=100;const before=JSON.stringify(g.s);store.setItem=()=>{throw Error('quota');};assert.equal(g.craft('quota'),false);assert.equal(JSON.stringify(g.s),before);assert.equal(g.notice,'error.storage');});
test('pet hatch uses persisted readiness and blocks duplicate claims',()=>{let now=2000000000000;const store=memory(),g=new Game(store,()=>now);g.s.maxStage=8;assert.ok(g.hatch('egg1'));assert.equal(g.hatch('egg2'),false);const reopened=new Game(store,()=>now);assert.equal(reopened.hatch('egg3'),false);now+=14400000;assert.ok(reopened.hatch('egg4'));});
test('skill drafts validate prerequisites and do not apply on failure',()=>{const g=game();g.s.sp=20;const draft=Array(18).fill(0);draft[1]=1;assert.equal(g.applySkills(draft,'bad'),false);assert.equal(g.s.sp,20);draft[0]=3;assert.ok(g.applySkills(draft,'good'));assert.equal(g.s.sp,13);assert.ok(g.applySkills(Array(18).fill(0),'reset'));assert.equal(g.s.sp,20);});
test('spells enforce level, mana and cooldown',()=>{const g=game();assert.equal(g.cast(0),false);g.s.run.master=350;assert.ok(g.cast(5));assert.equal(g.s.run.mana,76);assert.equal(g.cast(5),false);g.tick(1);assert.equal(g.s.run.spells[5],59);assert.equal(g.s.run.cooldowns[5],19);});
test('daily claim can be received once per day, including after reload',()=>{let now=2000000000000;const store=memory(),g=new Game(store,()=>now);assert.ok(g.claimDaily(0));assert.equal(g.claimDaily(0),false);const reopened=new Game(store,()=>now);assert.equal(reopened.claimDaily(0),false);now+=86400000;reopened.tick(.1);assert.ok(reopened.claimDaily(0));});
test('offline reward cannot be collected twice and is capped',()=>{let now=2000000000000;const store=memory(),g=new Game(store,()=>now);g.s.run.heroes[0]=10;g.persist();now+=100*86400000;const resumed=new Game(store,()=>now);assert.ok(resumed.s.offline>A.ZERO);const reward=resumed.s.offline;assert.ok(resumed.collectOffline('offline1'));assert.equal(resumed.s.offline,A.ZERO);assert.equal(resumed.collectOffline('offline2'),false);assert.ok(reward<10);assert.equal(new Game(store,()=>now).s.offline,A.ZERO);});
test('artifact discovery and upgrades debit relics atomically',()=>{const g=game();g.s.relics=A.amount(100);assert.ok(g.discover('d1'));const i=g.s.artifacts.findIndex(Boolean);assert.ok(g.upgradeArtifact(i,'a1'));assert.equal(g.s.artifacts[i],2);assert.equal(g.discover('d1'),false);});
test('raid deck locks during attack and part damage respects armor',()=>{const g=game();g.s.maxStage=100;g.s.portal=3;assert.ok(g.startRaid());const before=[...g.s.deck];g.setDeck(6);assert.deepEqual(g.s.deck,before);const armor=g.raid.armor[0],hp=g.raid.hp[0];g.raidTap(0);assert.ok(g.raid.armor[0]<armor);assert.equal(g.raid.hp[0],hp);g.raid.seconds=.1;g.tick(.2);assert.ok(g.raid.ended);assert.ok(g.claimRaid('r1'));assert.equal(g.claimRaid('r2'),false);});
test('event rewards and tile reveal cannot be duplicated',()=>{const g=game();g.s.eventTokens=1000;assert.ok(g.claimEvent(0));assert.equal(g.claimEvent(0),false);assert.ok(g.revealTile(0,'tile1'));const tokens=g.s.eventTokens;assert.equal(g.revealTile(0,'tile2'),false);assert.equal(g.s.eventTokens,tokens);});
test('late content gates and currency types remain distinct',()=>{const g=game();g.s.souls=100;assert.equal(g.summon('s0'),false);g.s.maxStage=100000;assert.ok(g.summon('s1'));assert.equal(g.s.souls,90);g.s.geodes=1;assert.ok(g.crack('g1'));assert.equal(g.s.geodes,0);assert.equal(g.monument(0,'m0'),false);});
test('Korean and English have identical nonempty keys and placeholders',()=>{const ko=translations.ko,en=translations.en;assert.deepEqual(Object.keys(ko).sort(),Object.keys(en).sort());const holes=s=>[...s.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort();for(const key of Object.keys(ko)){assert.ok(ko[key].trim(),key);assert.ok(en[key].trim(),key);assert.deepEqual(holes(ko[key]),holes(en[key]),key);if(key!=='locale.ko')assert.equal(/[가-힣]/.test(en[key]),false,key);}assert.throws(()=>t('en','missing'));assert.throws(()=>t('ko','hud.stage'));});
test('automated economy run reaches first prestige without debug currencies',()=>{const g=game();for(let second=0;second<7200&&g.s.run.stage<60;second++){g.buy(-1,-1);for(let i=0;i<24;i++)if(g.s.maxStage>=i*12)g.buy(i,-1);for(let tap=0;tap<5;tap++)g.tap();g.tick(1);if(g.s.run.bossFailed)g.toggleBoss();}assert.ok(g.s.run.stage>=60,`Reached stage ${g.s.run.stage}`);assert.ok(g.prestige('first'));});
test('spell selection cancels active effects and multicast respects cap and mana',()=>{const g=game();g.s.run.master=550;assert.ok(g.cast(3));g.s.run.mana=120;assert.ok(g.cast(3));assert.equal(g.s.run.stacks[3],2);g.s.run.mana=120;assert.ok(g.cast(3));assert.equal(g.s.run.stacks[3],3);g.s.run.mana=120;assert.equal(g.cast(3),false);assert.ok(g.selectSpell(3,9));assert.equal(g.s.run.spells[3],0);assert.equal(g.s.spellSlots[3],9);assert.equal(g.selectSpell(2,9),false);});
test('salvage refunds investments, removes effect, and preserves rebuy state',()=>{const g=game();g.s.relics=A.amount(1000);g.discover('discover');const i=g.s.artifacts.findIndex(Boolean);g.upgradeArtifact(i,'upgrade');const before=g.s.relics;assert.ok(g.salvageArtifact(i,'salvage'));assert.equal(g.s.artifacts[i],0);assert.ok(g.s.relics>before);assert.ok(g.s.salvaged.includes(i));assert.ok(g.rebuyArtifact(i,'rebuy'));assert.equal(g.s.artifacts[i],1);assert.equal(g.s.salvaged.includes(i),false);});
test('enchanted relics cannot be salvaged',()=>{const g=game();g.s.artifacts.fill(1);g.s.relics=A.amount(10000);assert.ok(g.enchantArtifact(0,'enchant'));assert.equal(g.salvageArtifact(0,'salvage'),false);assert.equal(g.s.artifacts[0],1);});
test('achievement tiers scale and cannot claim before the next threshold',()=>{const g=game();g.s.totalTaps=100;assert.ok(g.claimAchievement(0,'achievement1'));assert.equal(g.claimAchievement(0,'achievement2'),false);g.s.totalTaps=200;assert.ok(g.claimAchievement(0,'achievement2'));});
test('previous saves migrate spell arrays without losing existing progress',()=>{const store=memory(),g=new Game(store);g.s.run.master=222;delete g.s.spellSlots;delete g.s.run.spellLevels;delete g.s.run.stacks;g.s.run.spells=g.s.run.spells.slice(0,6);g.s.run.cooldowns=g.s.run.cooldowns.slice(0,6);g.persist();const reopened=new Game(store);assert.equal(reopened.s.run.master,222);assert.equal(reopened.s.run.spells.length,10);assert.equal(reopened.s.spellSlots.length,6);});
test('corrupt input saves are backed up before a new save is created',()=>{const store=memory();store.setItem('ember-ascent-v1','not-json');const g=new Game(store,()=>2000000000000);assert.equal(store.getItem('ember-ascent-corrupt-2000000000000'),'not-json');assert.equal(g.notice,'error.save');});
test('user-facing Korean literals remain inside the translation catalog',()=>{const fs=require('node:fs');const source=fs.readFileSync('assets/scripts/GameApp.ts','utf8');assert.equal(/[가-힣]/.test(source),false);const calls=[...source.matchAll(/this\.(?:label|button)\([^,]+,\s*(['"])([^'"]*)\1/g)];for(const match of calls)assert.equal(/[A-Za-z가-힣]/.test(match[2]),false,`Hardcoded UI: ${match[2]}`);});
test('fairy rewards remain rate limited across reload and UI rebuild',()=>{const store=memory(),g=new Game(store,()=>2000000000000);assert.ok(g.claimFairy('fairy1'));assert.equal(g.claimFairy('fairy2'),false);const reopened=new Game(store,()=>2000000000000);assert.equal(reopened.claimFairy('fairy3'),false);});
const {Expansion}=require('../.test-output/Expansion.js');
test('memory pairs consume attempts, reward once, and reject duplicate tiles',()=>{const g=game(),e=new Expansion(g);g.s.maxStage=8;assert.ok(e.petTile(0,'tile-a'));assert.ok(e.petTile(13,'tile-b'));assert.equal(g.s.extra.petEnergy,15);assert.equal(g.s.pets[0],1);assert.equal(e.petTile(13,'tile-c'),false);assert.equal(e.petMilestone(-1,'invalid-target'),false);});
test('mail expiry, protection and duplicate receipt are enforced',()=>{const g=game(),e=new Expansion(g),before=g.s.gems;assert.equal(e.deleteMail('welcome','delete-first'),false);assert.ok(e.claimMail('welcome','mail-first'));assert.equal(g.s.gems,before+25);assert.equal(e.claimMail('welcome','mail-second'),false);assert.ok(e.deleteMail('welcome','delete-after'));});
test('batch soul summoning and leveling preserve research points and damage',()=>{const g=game(),e=new Expansion(g);g.s.maxStage=100000;g.s.souls=100;assert.ok(e.summon(10,1,'ten'));assert.equal(g.s.souls,0);assert.equal(g.s.extra.summonCount,10);const damage=g.tapDamage();assert.ok(e.levelTitans(Array.from({length:120},(_,i)=>i),'levels'));assert.ok(g.tapDamage()>=damage);assert.ok(g.upgradeResearch(0,'research'));assert.equal(g.s.research[0],1);});
test('season rollover resets seasonal investments and creates only one mail',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),e=new Expansion(g);g.s.maxStage=180000;g.s.run.stage=180000;g.s.mementos=A.amount(10000);assert.ok(g.monument(0,'monument'));e.sync();now+=28*86400000;e.sync();e.sync();assert.equal(g.s.monuments[0],0);assert.equal(g.s.extra.mails.filter(m=>m.title==='extra.mail.season').length,1);assert.equal(g.s.extra.mails.filter(m=>m.title==='extra.mail.event').length,1);});
test('monument salvage refunds exact investment and blocks enchanted monument',()=>{const g=game(),e=new Expansion(g);g.s.maxStage=180000;g.s.mementos=A.amount(10);g.monument(0,'invest');assert.ok(e.salvageMonument(0,'refund'));assert.ok(Math.abs(10**g.s.mementos-9.8)<1e-9);g.s.monuments[0]=1;g.s.extra.monumentEnchanted[0]=1;assert.equal(e.salvageMonument(0,'protected'),false);});
test('ascension requires threshold and resets on rebirth',()=>{const g=game(),e=new Expansion(g);assert.equal(e.ascend(0,'locked'),false);g.s.run.heroes[0]=1000;assert.ok(e.ascend(0,'ascend'));assert.equal(g.s.run.heroes[0],1);g.s.run.stage=60;assert.ok(g.prestige('rebirth'));assert.equal(g.s.extra.ascensions[0],0);});
test('festival transactions rollback insufficient costs and preserve deterministic RNG',()=>{const g=game(),e=new Expansion(g);let before=JSON.stringify(g.s);assert.equal(e.drop('no-tokens'),false);assert.equal(JSON.stringify(g.s),before);g.s.eventTokens=100;assert.ok(e.alchemy(1,2,'recipe'));assert.equal(g.s.eventTokens,70);assert.ok(e.alchemy(2,1,'recipe-again'));assert.equal(g.s.extra.recipes.length,1);assert.ok(e.drop('ball'));assert.equal(g.s.extra.dropHistory.length,8);assert.equal(g.s.eventTokens,15);});
test('collectibles reset daily, and invalid repeat claims never award',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),e=new Expansion(g);g.s.extra.dailyFairies=3;assert.ok(e.collectible(0,'collect'));assert.equal(e.collectible(0,'collect-again'),false);now+=86400000;e.sync();assert.equal(g.s.extra.dailyFairies,0);assert.equal(g.s.extra.collectionClaims.length,0);});
test('all statically referenced extension translations exist in both locales',()=>{const fs=require('node:fs');for(const file of ['assets/scripts/ExpansionUI.ts','assets/scripts/core/Expansion.ts','assets/scripts/GameApp.ts']){for(const [,key] of fs.readFileSync(file,'utf8').matchAll(/['"](extra\.[\w.]+)['"]/g)){if(key.endsWith('.'))continue;for(const locale of ['ko','en'])assert.ok(translations[locale][key],locale+'/'+key);}}});
test('selected blessing follows its identity after swapping and expires',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),e=new Expansion(g);const before=g.goldReward();assert.ok(e.swapPerk(0,7,'swap-gold'));assert.ok(e.usePerk(0,'use-gold'));assert.ok(Math.abs(g.goldReward()-before-Math.log10(2))<1e-10);const tap=g.tapDamage();assert.ok(e.swapPerk(0,8,'swap-all'));assert.ok(e.usePerk(0,'use-all'));assert.ok(g.tapDamage()>tap);now+=300001;assert.ok(Math.abs(g.goldReward()-before)<1e-10);});
test('online retries preserve the same idempotency key across lost responses and reload',async()=>{const {Online}=require('../.test-output/Online.js'),store=memory(),original=global.fetch;let firstKey;try{global.fetch=async(_url,init)=>{firstKey=JSON.parse(init.body).key;throw new Error('lost');};await assert.rejects(new Online(store).command('/guild/vault'),/online.unreachable/);global.fetch=async(_url,init)=>{assert.equal(JSON.parse(init.body).key,firstKey);return {ok:true,json:async()=>({ok:true})};};assert.deepEqual(await new Online(store).command('/guild/vault'),{ok:true});assert.equal(store.getItem('ember-online-pending'),'{}');}finally{global.fetch=original;}});
test('event path uses lifetime earnings and can be claimed again next season',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),e=new Expansion(g);g.s.extra.eventEarned=100;g.s.eventTokens=0;assert.ok(g.claimEvent(0));now+=28*86400000;e.sync();g.s.extra.eventEarned=100;assert.ok(g.claimEvent(0));assert.equal(g.claimEvent(0),false);});
test('solo battle survives reload and reward claim cannot be replayed after transaction eviction',()=>{let now=2000000000000;const store=memory(),g=new Game(store,()=>now);g.s.maxStage=100;g.startRaid();g.raidTap(0);g.persist();now+=31000;const restored=new Game(store,()=>now);assert.ok(restored.raid.ended);assert.equal(restored.raid.hits,1);assert.equal(restored.startRaid(),false);assert.ok(restored.claimRaid('solo-reward'));const dust=restored.s.dust;restored.s.transactions=[];restored.persist();const again=new Game(store,()=>now);assert.equal(again.claimRaid('another-key'),false);assert.equal(again.s.dust,dust);});
test('raid reward persistence failure rolls back claimed flag and permits retry',()=>{const store=memory(),g=new Game(store,()=>2000000000000);g.s.maxStage=100;g.startRaid();g.raidTap(0);g.raid.ended=true;const write=store.setItem;store.setItem=()=>{throw Error('quota');};assert.equal(g.claimRaid('fail'),false);assert.equal(g.raid.claimed,false);store.setItem=write;assert.ok(g.claimRaid('retry'));});
test('solo portal selection, immutable attack deck and daily reward are durable',()=>{const g=game(),e=new Expansion(g);g.s.maxStage=100;g.s.portal=3;assert.equal(g.startRaid(4),false);assert.ok(e.saveDeck(1,'save-preset'));g.s.deck=[3,4,5];assert.ok(e.loadDeck(1,'load-preset'));assert.deepEqual(g.s.deck,[0,1,2]);for(let p=1;p<=3;p++){assert.ok(g.startRaid(p));g.raid.hp.fill(0);g.raid.ended=true;assert.equal(e.loadDeck(0,'locked-'+p),false);assert.ok(g.claimRaid('clear-'+p));}assert.ok(e.dailyPortal('daily-solo'));assert.equal(e.dailyPortal('daily-solo-again'),false);assert.equal(g.s.portal,4);assert.equal(g.s.fragments.reduce((a,b)=>a+b,0),19);});
test('equipment milestones cannot re-drop and sparse crafting does not grant false set bonuses',()=>{const g=game();g.s.maxStage=15;g.unlock();g.unlock();assert.equal(g.s.equipment.length,1);g.s.shards=100;for(let set=1;set<=5;set++)assert.ok(g.craft('sparse-'+set,set,0));const before=g.bonus(0);assert.equal(g.craft('duplicate',1,0),false);assert.ok(g.craft('default'));assert.ok(g.s.setHistory.includes(0));assert.ok(Math.abs((g.bonus(0)-before)-Math.log10(1.030/1.025))<1e-12);});
test('scientific display handles large logarithmic currency without overflow',()=>{assert.equal(A.fmt(A.amount(15000),true),'1.50e4');assert.equal(A.fmt(10000,true),'1.00e10000');assert.equal(A.fmt(A.ZERO,true),'0');});
test('unlock announcements queue once and equipment result list survives reload',()=>{const store=memory(),g=new Game(store,()=>2000000000000);g.s.maxStage=15;g.unlock();g.unlock();assert.deepEqual(g.s.extra.unlockNotices,[8,15]);assert.equal(g.s.extra.unseenEquipment.length,1);g.persist();const again=new Game(store,()=>2000000000000);assert.deepEqual(again.s.extra.unlockNotices,[8,15]);assert.equal(again.s.extra.unseenEquipment[0],again.s.equipment[0].id);});
test('monument discovery spends atomically and never duplicates owned monuments',()=>{const g=game(),e=new Expansion(g);g.s.maxStage=180000;g.s.mementos=A.amount(10000);for(let i=0;i<12;i++)assert.ok(e.discoverMonument('discover-monument-'+i));assert.ok(g.s.monuments.every(n=>n===1));assert.equal(e.discoverMonument('discover-extra'),false);});
test('raid deadline rejects hits even when the game frame timer was paused',()=>{let now=2000000000000;const g=new Game(undefined,()=>now);g.s.maxStage=100;g.startRaid();now+=31000;g.raidTap(0);assert.equal(g.raid.hits,0);assert.ok(g.raid.ended);});
test('reward announcements persist without granting the same reward twice',()=>{const store=memory(),g=new Game(store,()=>2000000000000);g.s.gems=100;assert.ok(g.buyDeal(2,'weapon-chest'));assert.equal(g.s.extra.rewardNotices[0].kind,'weapon');const hero=g.s.extra.rewardNotices[0].value;assert.equal(g.s.weapons[hero],1);const restored=new Game(store,()=>2000000000000);assert.equal(restored.s.extra.rewardNotices[0].value,hero);assert.equal(restored.buyDeal(2,'weapon-chest'),false);assert.equal(restored.s.weapons[hero],1);});
test('set completion and milestone announcements are generated only once',()=>{const g=game();g.s.shards=100;for(let i=0;i<5;i++)g.craft('notice-craft-'+i,0,i);assert.equal(g.s.extra.rewardNotices.filter(n=>n.kind==='equipmentSet').length,1);g.s.maxStage=100;g.unlock();g.unlock();const n=g.s.extra.rewardNotices.filter(n=>n.kind==='milestone');assert.equal(n.length,1);assert.equal(n[0].count,2);});
test('unlisted milestone values cannot mint arbitrary rewards',()=>{const g=game(),gems=g.s.gems;assert.equal(g.claimMilestone(-1),false);assert.equal(g.claimMilestone(1),false);assert.equal(g.s.gems,gems);g.s.maxStage=8;assert.ok(g.claimMilestone(8));});
const {Monetization,PRODUCTS}=require('../.test-output/Monetization.js');
test('reference purchase catalog preserves Korean storefront prices without web bonus mixing',()=>{assert.deepEqual(PRODUCTS.filter(p=>p.kind==='consumable').map(p=>[p.gems,p.krw]),[[180,3300],[500,7700],[1200,17000],[3100,44000],[6500,77000],[14000,149000]]);assert.equal(PRODUCTS.find(p=>p.id==='season_pass').krw,17000);assert.equal(PRODUCTS.find(p=>p.id==='starter_bundle').configured,false);});
test('unconnected billing cannot grant currency and cancelled purchase has no effect',async()=>{const g=game(),m=new Monetization(g,{}),before=g.s.gems;await assert.rejects(m.purchase('diamonds_500'),/money.storeUnavailable/);m.billing={purchase:async()=>({status:'cancelled'}),catalog:async()=>[],restore:async()=>[]};assert.equal(await m.purchase('diamonds_500'),'cancelled');assert.equal(g.s.gems,before);});
test('verified monetization rewards survive reload and cannot duplicate after transaction eviction',()=>{const store=memory(),g=new Game(store,()=>2000000000000),m=new Monetization(g,{}),grant={id:'receipt-test',kind:'purchase',product:'diamonds_500',gems:500,vipPoints:125,passUntil:0};assert.ok(m.apply(grant));g.s.transactions=[];g.persist();const r=new Game(store,()=>2000000000000);assert.equal(new Monetization(r,{}).apply(grant),false);assert.equal(r.s.gems,600);assert.equal(r.s.extra.commerce.vipPoints,125);});
test('ad effects apply only once, expire at server times, and respect inventory capacity',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),m=new Monetization(g,{});const grant=(id,placement,fields={})=>({id,kind:'ad',placement,gems:0,vipPoints:0,passUntil:0,...fields});g.s.run.mana=0;assert.ok(m.apply(grant('mana','fairy_mana')));assert.equal(g.s.run.mana,30);const cost=g.upgradeCost(-1),damage=g.tapDamage();assert.ok(m.apply(grant('discount','fairy_discount',{discountUntil:now+60000})));assert.equal(g.upgradeCost(-1),cost-1);assert.ok(m.apply(grant('boost','mega_boost',{boostUntil:now+14400000})));assert.ok(Math.abs(g.tapDamage()-damage-Math.log10(2))<1e-12);now+=14400001;assert.equal(g.tapDamage(),damage);assert.equal(g.upgradeCost(-1),cost);for(let i=0;i<100;i++)g.drop();assert.equal(m.apply(grant('chest','shop_chest')),false);assert.equal(g.s.claims.includes('commerce:chest'),false);});
test('failed reward save rolls back and delivery retry acknowledges only durable grants',async()=>{const store=memory(),g=new Game(store,()=>2000000000000),grant={id:'retry-proof',kind:'ad',placement:'fairy_diamond',gems:10,vipPoints:0,passUntil:0},acks=[];const m=new Monetization(g,{request:async()=>[grant],command:async(p,d)=>acks.push(d.id)});const save=store.setItem;store.setItem=()=>{throw Error('quota');};await assert.rejects(m.deliver(),/error.storage/);assert.equal(acks.length,0);assert.equal(g.s.gems,100);store.setItem=save;await m.deliver();await m.deliver();assert.equal(g.s.gems,110);assert.equal(g.s.eventTokens,15);assert.equal(acks.length,2);});
test('current fairy spree effects stack independently and blacksmith beats equipped rare equipment',()=>{const g=game(),m=new Monetization(g,{}),base=g.tapDamage(),gold=g.goldReward(),grant=(id,placement,rest={})=>({id,kind:'ad',placement,gems:0,vipPoints:0,passUntil:0,...rest});assert.ok(m.apply(grant('spree-d','fairy_damage_spree',{damageSpreeUntil:g.now()+300000})));assert.equal(g.tapDamage(),base+1);assert.ok(m.apply(grant('spree-g','fairy_gold_spree',{goldSpreeUntil:g.now()+300000})));assert.equal(g.goldReward(),gold+1);for(let i=0;i<5;i++){const item=g.drop(i,1);item.power=1000;item.level=1000;g.equip(item.id);}assert.ok(m.apply(grant('smith','fairy_equipment')));const item=g.s.equipment[g.s.equipment.length-1];assert.equal(item.rarity,1);assert.ok(item.power>1000);assert.ok(item.level>1000);});
const B=require('../.test-output/Balance.js');
test('reference artifact discovery curve retains salvaged discoveries',()=>{const g=game();assert.equal(g.discoverCost(),0);g.s.artifacts[0]=1;assert.ok(Math.abs(g.discoverCost()-Math.log10(3))<1e-12);g.s.artifacts.fill(1,0,9);assert.ok(Math.abs(g.discoverCost()-Math.log10(148))<1e-12);g.s.gems=100;const before=g.discoverCost();assert.ok(g.salvageArtifact(0,'balance-salvage'));assert.equal(g.discoverCost(),before);assert.ok(g.rebuyArtifact(0,'balance-rebuy'));assert.equal(g.discoverCost(),before);assert.ok(B.ARTIFACT_DISCOVERY_COSTS.every((v,i,a)=>Number.isFinite(v)&&(!i||v>a[i-1])));});
test('gemstone rarity opens reference slots at exact boundaries',()=>{assert.deepEqual([0,1,99,100,199,200,399,400,499,500].map(B.gemstoneSlots),[0,1,1,1,1,2,2,3,3,4]);assert.equal(B.gemstoneBonus(0,199,'hero'),0);assert.ok(B.gemstoneBonus(0,200,'hero')>0);assert.equal(B.gemstoneBonus(0,399,'gold'),0);assert.ok(B.gemstoneBonus(0,400,'gold')>0);});
test('growth types affect only their assigned economy or damage channels',()=>{const g=game(),base=[g.bonus(1),g.bonus(2),g.bonus(3)];g.s.stones[2]=50;assert.equal(g.bonus(1),base[0]);assert.equal(g.bonus(2),base[1]);assert.ok(g.bonus(3)>base[2]);g.s.extra.titanLevels[0]=10;g.s.monuments[0]=5;g.s.extra.monumentEnchanted[0]=1;assert.ok(g.bonus(1)>base[0]);assert.equal(g.bonus(2),base[1]);g.s.research[1]=3;g.s.extra.mysticResearch[1]=2;assert.ok(Math.abs(g.bonus(2)-base[1]-.085)<1e-12);});
test('growth report sums the same contributions used by combat and survives save',()=>{const store=memory(),g=new Game(store,()=>2000000000000);g.s.stones[0]=500;g.s.extra.titanLevels[0]=3;g.s.monuments[0]=4;const before=g.bonus(1),rows=g.growthContributions('tap');assert.ok(rows.every(r=>Number.isFinite(r.log)));assert.equal(rows.reduce((sum,r)=>sum+r.log,0),before);g.persist();const loaded=new Game(store,()=>2000000000000);assert.equal(loaded.bonus(1),before);assert.deepEqual(loaded.growthContributions('tap'),rows);});
test('invalid growth IDs cannot consume resources or poison saves',()=>{const g=game(),e=new Expansion(g);g.s.extra.geodesOpened=1000;g.s.extra.summonCount=1000;g.s.maxStage=180000;g.s.mementos=A.amount(1e8);const before=JSON.stringify(g.s);assert.equal(e.mysticNode(12,'bad-mystic'),false);assert.equal(g.upgradeResearch(-1,'bad-research'),false);assert.equal(g.monument(0.5,'bad-monument'),false);assert.equal(e.gemMilestone(24,100,'bad-gem'),false);assert.equal(JSON.stringify(g.s),before);});
test('public previews never default to a visitor localhost and endpoint credentials are rejected',()=>{const {apiEndpoint}=require('../.test-output/Online.js');assert.equal(apiEndpoint({hostname:'readercar.github.io',origin:'https://readercar.github.io'}),'');assert.equal(apiEndpoint({hostname:'localhost',origin:'http://localhost:8788'}),'http://localhost:8788/api');assert.equal(apiEndpoint(undefined,'https://example.com/api/'),'https://example.com/api');assert.throws(()=>apiEndpoint(undefined,'https://user:pass@example.com/api'));assert.throws(()=>apiEndpoint(undefined,'http://example.com/api'));});
test('an unconfigured public service fails before issuing any request',async()=>{const {Online}=require('../.test-output/Online.js'),o=new Online(memory()),old=global.fetch;o.base='';let fetched=false;global.fetch=async()=>{fetched=true;throw Error('unexpected');};try{await assert.rejects(o.request('/account'),/online.unconfigured/);assert.equal(fetched,false);}finally{global.fetch=old;}});
test('event rollover mails only earned unclaimed free rewards once',()=>{let now=2000000000000;const g=new Game(memory(),()=>now),e=new Expansion(g);g.s.eventTokens=300;g.s.extra.eventEarned=300;assert.ok(g.claimEvent(0));now+=28*86400000;e.sync();const mail=g.s.extra.mails.find(m=>m.title==='extra.mail.event');assert.equal(mail.gems,33);assert.equal(mail.shards,10);assert.equal(g.s.eventTokens,0);assert.ok(e.claimMail(mail.id,'rollover-mail'));assert.equal(e.claimMail(mail.id,'rollover-mail-duplicate'),false);e.sync();assert.equal(g.s.extra.mails.filter(m=>m.title==='extra.mail.event').length,1);});
test('event claims and board reject invented indices without changing state',()=>{const g=game();g.s.eventTokens=10000;const before=JSON.stringify(g.s);for(const i of [-1,.5,10,999])assert.equal(g.claimEvent(i),false);for(const i of [-1,.5,16,999])assert.equal(g.revealTile(i,'invalid-tile-'+i),false);assert.equal(JSON.stringify(g.s),before);});
const live=require('../.test-output/LiveOps.js');
test('update policy normalizes versions, exact targets and safe URLs',()=>{const p={notices:[],minimumVersion:{web:'1.2',android:'0',ios:'0'},storeUrls:{web:'https://example.com/update',android:'',ios:''}};assert.equal(live.compareVersions('1.2','1.2.0'),0);assert.equal(live.requiresUpdate(p,'web','1.1'),true);assert.equal(live.requiresUpdate(p,'web','1.3'),false);p.requiredVersion={web:'1.2'};assert.equal(live.requiresUpdate(p,'web','1.3'),true);assert.equal(live.requiresUpdate(p,'web','1.2.0'),false);assert.equal(live.validatePolicy(p),p);p.storeUrls.web='javascript:alert(1)';assert.throws(()=>live.validatePolicy(p));assert.throws(()=>live.compareVersions('1.bad','1'));});
test('mail expires at exact boundary in both inboxes and keeps old shorter expiry',()=>{let now=2000000000000;const g=new Game(undefined,()=>now),e=new Expansion(g);const mail=g.s.extra.mails[0];assert.equal(mail.expires-now,30*86400000);assert.ok(e.claimMail(mail.id,'new-mail-claim'));now=mail.expires;e.sync();assert.equal(g.s.extra.mails.some(m=>m.id===mail.id),false);assert.equal(e.claimMail(mail.id,'expired-mail'),false);assert.equal(live.mailExpiry({expires:10}),10);assert.equal(live.mailExpiry({created:0,expires:100*86400000}),30*86400000);});
test('mail receipt storage failure rolls back reward and confirmed state',()=>{const store=memory(),g=new Game(store),e=new Expansion(g),before=g.s.gems;store.setItem=()=>{throw Error('quota');};assert.equal(e.claimMail('welcome','mail-storage-failure'),false);assert.equal(g.s.gems,before);assert.equal(g.s.extra.mails[0].claimed,false);});
test('heroes wind up before a discrete hit and retain average DPS',()=>{
 const g=game();g.s.run.heroes[0]=1;g.s.run.hp=A.amount(100000);const initial=g.s.run.hp;
 g.tick(.9);assert.equal(g.s.run.hp,initial);assert.deepEqual(g.heroEvents,[]);
 g.tick(.01);assert.equal(g.s.run.hp,initial);assert.equal(g.heroEvents[0].phase,'attack');assert.equal(g.heroEvents[0].hero,0);
 g.tick(.23);assert.equal(g.s.run.hp,initial);
 g.tick(.01);assert.equal(g.heroEvents[0].phase,'hit');assert.equal(g.heroEvents[0].damage,A.mul(g.heroDPS(0),1.15));assert.equal(g.s.run.hp,A.sub(initial,g.heroEvents[0].damage));
 const hp=g.s.run.hp;g.tick(.5);assert.equal(g.s.run.hp,hp);
});
test('each recruited hero emits its own hit and rebirth clears attack clocks',()=>{
 const g=game();g.s.run.hp=A.amount(1000000);g.s.run.heroes[0]=g.s.run.heroes[1]=1;
 g.tick(1);g.tick(.15);assert.deepEqual(g.heroEvents.filter(e=>e.phase==='hit').map(e=>e.hero),[0,1]);
 g.tick(.9);g.s.run.stage=60;assert.ok(g.prestige('attack-reset'));g.s.run.heroes[0]=1;const hp=g.s.run.hp;
 g.tick(.2);assert.equal(g.s.run.hp,hp);assert.deepEqual(g.heroEvents,[]);
});
test('reference spell costs use level tables and stop at the source cap',()=>{
 const g=game();g.s.run.master=550;assert.equal(g.spellMana(0),8);assert.equal(g.spellMana(4),44);assert.equal(g.spellUpgradeCost(4),A.amount(533));
 g.s.run.gold=A.amount(1e100);assert.ok(g.upgradeSpell(4));assert.equal(g.spellMana(4),45);g.s.run.spellLevels[4]=30;const gold=g.s.run.gold;assert.equal(g.upgradeSpell(4),false);assert.equal(g.s.run.gold,gold);assert.equal(g.spellMana(4),186);
});
test('War Cry speeds hit cadence and keeps damage tied to individual hits',()=>{
 const g=game();g.s.run.heroes[0]=1;g.s.run.master=300;g.s.run.hp=A.amount(1e6);assert.ok(g.cast(4));assert.equal(g.heroAttackRate(),2);const initial=g.s.run.hp;
 g.tick(.46);assert.equal(g.s.run.hp,initial);assert.equal(g.heroEvents[0].phase,'attack');assert.equal(g.heroEvents[0].windup,.12);
 g.tick(.115);assert.equal(g.heroEvents[0].phase,'hit');assert.equal(g.heroEvents[0].damage,A.mul(g.heroDPS(0),1.15/2));
 g.s.run.spellLevels[4]=30;assert.equal(g.heroAttackRate(),16.2);g.s.run.spells[4]=0;assert.equal(g.heroAttackRate(),1);
});
test('Crystal gates all type slots at reference thresholds and migrates old slots',()=>{
 const store=memory(),g=new Game(store);g.s.extra.crystal=[0,1,2];g.persist();const restored=new Game(store);assert.deepEqual(restored.s.extra.crystal,[0,-1,-1,-1,-1,1,-1,-1,-1,-1,2,-1,-1,-1,-1]);
 const e=new Expansion(restored);restored.s.cards.fill(0);restored.s.cards[0]=999;assert.equal(e.crystalSlots(0),0);assert.equal(e.crystal(0,3,'locked'),false);
 for(const [total,expected] of [[1000,[1,1,1]],[1200,[1,1,2]],[1400,[2,1,2]],[1600,[2,2,2]],[7000,[5,5,5]]]){restored.s.cards[0]=total;assert.deepEqual([0,1,2].map(t=>e.crystalSlots(t)),expected);}
 restored.s.cards[0]=1000;assert.ok(e.crystal(10,5,'support'));assert.equal(e.crystal(11,8,'locked-support'),false);assert.equal(e.crystal(1,3,'locked-burst'),false);assert.equal(e.crystal(0,1,'wrong-type'),false);
});
test('Crystal sixth-highest level is type-specific; Solo boosts unassigned cards',()=>{
 const g=game(),e=new Expansion(g);g.s.cards.fill(200);[0,3,6,9,12,15].forEach((c,i)=>g.s.cards[c]=[150,140,130,120,110,7][i]);assert.equal(e.crystalLevel(0),7);assert.equal(e.crystalLevel(1),200);assert.equal(e.boostedLevel(15,true),7);
 // Extend the fixture with a seventh same-type card to distinguish the sixth from the minimum.
 g.s.cards.push(1);assert.equal(e.boostedLevel(18),1);assert.equal(e.boostedLevel(18,true),7);
 g.s.extra.crystal[0]=18;assert.equal(e.boostedLevel(18),7);
});
test('accelerated hero hits do not disappear at low frame rates',()=>{
 const build=()=>{const g=game();g.s.run.heroes[0]=1;g.s.run.spellLevels[4]=30;g.s.run.spells[4]=30;g.s.run.hp=A.amount(1e9);return g;};
 const slow=build(),fast=build();const hp=slow.s.run.hp;slow.tick(1);for(let i=0;i<100;i++)fast.tick(.01);assert.equal(slow.heroEvents.filter(e=>e.phase==='hit').length,14);assert.ok(Math.abs(slow.s.run.hp-fast.s.run.hp)<1e-10);assert.ok(slow.s.run.hp<hp);
});
test('Heavenly Strike three-second field cannot bypass cooldown through multicast',()=>{
 const g=game();g.s.run.master=550;g.s.run.hp=A.amount(1e9);assert.ok(g.cast(0));assert.equal(g.s.run.mana,112);assert.equal(g.cast(0),false);assert.equal(g.s.run.mana,112);for(let i=0;i<3;i++)g.tick(1);assert.ok(g.cast(0));
});

const Entry=require('../.test-output/EntryPolicy.js');
test('entry consent rejects legacy, missing or invalid mandatory receipts',()=>{assert.equal(Entry.parseConsent('accepted'),null);assert.equal(Entry.parseConsent(JSON.stringify({...Entry.consentReceipt(1),privacy:false})),null);assert.equal(Entry.parseConsent(JSON.stringify({...Entry.consentReceipt(1),version:'old'})),null);assert.deepEqual(Entry.parseConsent(JSON.stringify(Entry.consentReceipt(2))),Entry.consentReceipt(2));});
test('first expedition guide persists, advances on actions and resumes after restore',()=>{const g=game(),s=g.s;assert.equal(s.tutorial.step,0);Entry.tutorialAdvance(s,'begin');assert.equal(s.tutorial.step,1);s.totalTaps=2;assert.equal(Entry.tutorialAdvance(s,'progress'),false);s.totalTaps=3;Entry.tutorialAdvance(s,'progress');s.run.master=2;Entry.tutorialAdvance(s,'progress');assert.equal(s.tutorial.step,3);Entry.tutorialAdvance(s,'heroes');s.run.heroes[0]=1;Entry.tutorialAdvance(s,'progress');Entry.tutorialAdvance(s,'fold');const saved=JSON.parse(JSON.stringify(s));g.migrate(saved);assert.equal(saved.tutorial.step,6);Entry.tutorialAdvance(saved,'unfold');assert.equal(saved.tutorial.step,Entry.TUTORIAL_DONE);});
test('replay uses new actions and migration keeps existing players out of first-play guide',()=>{const g=game(),s=g.s;s.totalTaps=100;s.totalKills=20;s.run.master=30;s.run.heroes[0]=15;delete s.tutorial;g.migrate(s);assert.equal(s.tutorial.step,7);Entry.replayTutorial(s);Entry.tutorialAdvance(s,'begin');assert.equal(Entry.tutorialAdvance(s,'progress'),false);s.totalTaps+=3;Entry.tutorialAdvance(s,'progress');assert.equal(s.tutorial.step,2);assert.equal(Entry.tutorialAdvance(s,'progress'),false);s.run.master++;Entry.tutorialAdvance(s,'progress');assert.equal(s.tutorial.step,3);});
test('progressive navigation opens only at milestones and stays open after rebirth',()=>{const s=game().s;assert.deepEqual([0,1,2,3,4,5].map(i=>Entry.tabUnlocked(s,i)),[true,true,false,false,false,false]);for(const [tab,stage] of [[5,3],[3,8],[2,15],[4,60]]){s.maxStage=stage-1;assert.equal(Entry.tabUnlocked(s,tab),false);s.maxStage=stage;assert.equal(Entry.tabUnlocked(s,tab),true);s.run.stage=1;assert.equal(Entry.tabUnlocked(s,tab),true);}s.maxStage=15;assert.equal(Entry.featureUnlocked(s,'menu.cards'),false);assert.equal(Entry.featureUnlocked(s,'extra.monuments'),false);assert.equal(Entry.featureUnlocked(s,'extra.petPuzzle'),true);});
test('portrait proportions reserve management space and give extra height to the battlefield',()=>{assert.equal(Entry.designHeight(360,640),854);assert.equal(Entry.designHeight(320,640),960);assert.equal(Entry.designHeight(390,844),1039);assert.equal(Entry.designHeight(1920,817),960);});
test('first-use receipts survive restore, language changes and prestige while replay clears them',()=>{const g=game();assert.equal(Entry.tutorialComplete(g.s,'use:slot.0:action.equip'),true);assert.equal(Entry.tutorialComplete(g.s,'use:slot.0:action.equip'),false);g.s.maxStage=g.s.run.stage=60;g.s.locale='en';assert.ok(g.prestige('guide-prestige'));const restored=JSON.parse(JSON.stringify(g.s));g.migrate(restored);g.validate(restored);assert.ok(Entry.tutorialSeen(restored,'use:slot.0:action.equip'));Entry.replayTutorial(restored);assert.equal(Entry.tutorialSeen(restored,'use:slot.0:action.equip'),false);});
test('first-use tab queue exposes only unlocked tabs in progression order',()=>{const g=game();assert.equal(Entry.nextTutorialTab(g.s),undefined);g.s.maxStage=15;assert.equal(Entry.nextTutorialTab(g.s),5);Entry.tutorialComplete(g.s,'tab:5');assert.equal(Entry.nextTutorialTab(g.s),3);Entry.tutorialComplete(g.s,'tab:3');assert.equal(Entry.nextTutorialTab(g.s),2);Entry.tutorialComplete(g.s,'tab:2');assert.equal(Entry.nextTutorialTab(g.s),undefined);g.s.maxStage=60;assert.equal(Entry.nextTutorialTab(g.s),4);});
test('failed skill use does not finish its first-use guide',()=>{const g=game();assert.equal(g.cast(0),false);assert.equal(Entry.tutorialSeen(g.s,'first:spell'),false);g.s.run.master=100;g.s.run.mana=120;assert.ok(g.cast(0));assert.ok(Entry.tutorialSeen(g.s,'first:spell'));});
test('malformed first-use receipts are rejected without rejecting older saves',()=>{const g=game();delete g.s.tutorial.completed;assert.doesNotThrow(()=>g.validate(g.s));g.s.tutorial.completed=['tab:5','tab:5'];assert.throws(()=>g.validate(g.s),/tutorial.completed/);g.s.tutorial.completed=['invalid key'];assert.throws(()=>g.validate(g.s),/tutorial.completed/);});

const {feedbackSnapshot,feedbackDiff}=require('../.test-output/Feedback.js');
test('feedback only reports actual gains and never a failed or duplicate claim',()=>{const g=game();g.s.run.gold=A.ZERO;let before=feedbackSnapshot(g);assert.equal(g.buy(-1,1),false);assert.deepEqual(feedbackDiff(before,feedbackSnapshot(g)).rewards,[]);assert.equal(feedbackDiff(before,feedbackSnapshot(g)).growth.length,0);before=feedbackSnapshot(g);g.claimDaily(0);const diff=feedbackDiff(before,feedbackSnapshot(g));assert.equal(diff.rewards.find(e=>e.key==='feedback.gems').value,25);before=feedbackSnapshot(g);g.claimDaily(0);assert.equal(feedbackDiff(before,feedbackSnapshot(g)).rewards.length,0);});
test('feedback reports batched levels and exact log-space reward quantities',()=>{const g=game();g.s.run.gold=A.amount(1e6);let before=feedbackSnapshot(g);g.buy(-1,10);let diff=feedbackDiff(before,feedbackSnapshot(g));assert.equal(diff.growth.find(e=>e.key==='master.title').value,10);assert.ok(diff.tap);assert.equal(diff.rewards.length,0);g.s.offline=A.amount(250);before=feedbackSnapshot(g);g.collectOffline('feedback-offline');diff=feedbackDiff(before,feedbackSnapshot(g));assert.ok(Math.abs(Math.pow(10,diff.rewards.find(e=>e.key==='feedback.gold').value)-250)<.001);assert.equal(feedbackDiff(before,feedbackSnapshot(g),false).rewards.length,0);});

const formation=require('../.test-output/BattleFormation.js');
test('military formation stays separated and wave count grows to thirty',()=>{
 const units=Array.from({length:9},(_,i)=>formation.allyPosition(i));
 for(let i=0;i<units.length;i++)for(let j=i+1;j<units.length;j++)assert.ok(Math.abs(units[i].x-units[j].x)>=60||Math.abs(units[i].y-units[j].y)>=70);
 let last=0;for(let stage=1;stage<=600;stage++){const n=formation.waveSize(stage);assert.ok(n>=last&&n<=30);last=n;for(let i=0;i<n;i++){const p=formation.enemyPosition(i,n);assert.ok(p.x>=40&&p.x+formation.soldierSize(p.y,true)/2<=240&&p.y+formation.soldierSize(p.y,true)<350);}}
 assert.equal(formation.waveSize(1),1);assert.equal(formation.waveSize(400),30);assert.equal(formation.waveSize(400,true),1);
 assert.equal(formation.survivingEnemies(30,.5),15);assert.equal(formation.survivingEnemies(30,0),0);assert.equal(formation.survivingEnemies(30,1),30);
});

const cheats=require('../.test-output/PrototypeCheats.js');
test('prototype reset creates a fully fresh save and fresh tutorial without changing backup',()=>{
 const g=game();g.s.run.master=500;g.s.run.heroes.fill(50);g.s.maxStage=400;g.s.claims=['daily.0'];g.s.tutorial.step=7;g.s.tutorial.completed=['tab:5'];g.s.equipment.push({id:1,slot:0,rarity:0,level:1,power:1,locked:false});
 const old=JSON.stringify(g.s),fresh=cheats.freshPrototype('en',g.now());g.validate(fresh);
 assert.equal(fresh.run.stage,1);assert.equal(fresh.run.master,1);assert.ok(fresh.run.heroes.every(v=>v===0));assert.equal(fresh.maxStage,1);assert.equal(fresh.tutorial.step,0);assert.deepEqual(fresh.claims,[]);assert.deepEqual(fresh.equipment,[]);assert.equal(fresh.locale,'en');assert.equal(fresh.offline,A.ZERO);assert.equal(JSON.stringify(g.s),old);
});
test('cheat presets clone progress, validate zones and replay uses fresh action baselines',()=>{
 const g=game(),original=JSON.stringify(g.s);g.validate(cheats.prototypeCheat(g.s,'funds'));const squad=cheats.prototypeCheat(g.s,'squad');g.validate(squad);assert.equal(squad.run.heroes.filter(v=>v>0).length,8);
 const advanced=cheats.prototypeCheat(g.s,'stage',400);assert.equal(advanced.run.stage,400);assert.equal(advanced.run.boss,false);assert.equal(advanced.run.hp,g.maxHP(400,false));assert.equal(advanced.tutorial.step,Entry.TUTORIAL_DONE);assert.throws(()=>cheats.prototypeCheat(g.s,'stage',999),/error.invalid/);
 advanced.totalTaps=100;const replay=cheats.prototypeCheat(advanced,'tutorial');assert.equal(replay.tutorial.step,0);assert.equal(replay.tutorial.tapBaseline,100);assert.equal(JSON.stringify(g.s),original);
});
test('independent hostile HP damages only the chosen slot and survives reload',()=>{
 const store=memory(),g=new Game(store);g.s.run.stage=30;g.s.run.hp=g.maxHP();g.resetEnemies();const before=[...g.enemyHealth()];
 g.damage(A.mul(before[3],.25),3);assert.ok(g.enemyHealth()[3]<before[3]);for(let i=0;i<6;i++)if(i!==3)assert.equal(g.enemyHealth()[i],before[i]);
 g.damage(100,3);assert.equal(g.enemyHealth()[3],A.ZERO);assert.equal(g.enemyHealth().filter(h=>h!==A.ZERO).length,5);assert.equal(g.s.totalKills,0);
 assert.ok(g.persist());const loaded=new Game(store);assert.deepEqual(loaded.enemyHealth(),g.enemyHealth());assert.equal(loaded.lastHit,-1);
});
test('wave rewards occur once after all independent enemies die; boss resets to one slot',()=>{
 const g=game();g.s.run.stage=400;g.s.run.kills=4;g.s.run.hp=g.maxHP();g.resetEnemies();const gold=g.s.run.gold;
 for(let i=0;i<29;i++){g.damage(1000,i);assert.equal(g.s.totalKills,0);assert.equal(g.s.run.gold,gold);}
 g.damage(1000,29);assert.equal(g.s.totalKills,1);assert.equal(g.s.run.boss,true);assert.equal(g.enemyHealth().length,1);assert.ok(g.s.run.gold>gold);
 g.s.run.bossLeft=.01;g.tick(.02);assert.equal(g.enemyHealth().length,30);assert.ok(g.enemyHealth().every(h=>h!==A.ZERO));
});
test('overkill retargets a dead slot without changing another living slot in the same hit',()=>{
 const g=game();g.s.run.stage=5;g.s.run.hp=g.maxHP();g.resetEnemies();const second=g.enemyHealth()[1];g.damage(100,0);assert.equal(g.lastHit,0);assert.equal(g.enemyHealth()[1],second);g.damage(A.mul(second,.1),0);assert.equal(g.lastHit,1);assert.ok(g.enemyHealth()[1]<second);
});

test('both factions share perspective with slightly larger male silhouettes',()=>{assert.equal(formation.soldierSize(65),96);assert.equal(formation.soldierSize(65,true),96*1.08);assert.ok(formation.soldierSize(215)<formation.soldierSize(65));assert.equal(formation.allyPosition(0).y,formation.enemyPosition(0,1).y);});
