const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{transformSync}=require('esbuild');
function load(file,imports){const module={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(file,'utf8'),{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,require:name=>{if(!(name in imports))throw Error(name);return imports[name];},setTimeout,clearTimeout});return module.exports;}
function fixture(session='guest'){
 const items=new Map([['tapwar-login-method','google'],['tapwar-consent-v2','accepted']]),calls=[];
 const storage={getItem:k=>items.get(k)||null,setItem:(k,v)=>items.set(k,v),removeItem:k=>items.delete(k)};
 const {EntryUI}=load('assets/scripts/EntryUI.ts',{'cc':{sys:{localStorage:storage}},'./UITheme':{UI:{}},'./FeedbackUI':{FeedbackUI:class {}},'./TutorialUI':{TutorialUI:class {}},'./core/EntryPolicy':{CONSENT_KEY:'tapwar-consent-v2',parseConsent:raw=>raw==='accepted'},'./core/LiveOps':{requiresUpdate:()=>false}});
 const a={isValid:true,draw(){},close(){},tr:k=>k,toast:k=>calls.push(k),game:{s:{locale:'ko'}},liveOps:{push:{choice:false}},cloud:{resume:async()=>{calls.push('resume');return session;},loginGoogle:async()=>calls.push('popup'),loginGuest:async()=>calls.push('new-guest')},operations:{local:false,useCloud:false,policy:async()=>({}),start:async value=>calls.push('start:'+value),flushErrors:async()=>{},save:async()=>calls.push('save'),endSession:async()=>calls.push('signout')}};
 const entry=new EntryUI(a);entry.frame=async()=>{};return {entry,a,items,calls};
}
for(const method of ['google','guest'])test(`Start Game resumes ${method} without popup/account creation`,async()=>{const {entry,items,calls}=fixture(method);await entry.login('guest',false,true);assert.equal(entry.playing,true);assert.equal(items.get('tapwar-login-method'),method);assert.deepEqual(calls,['resume','start:'+(method==='google')]);});
test('missing session returns to login without creating an account',async()=>{const {entry,calls}=fixture(null);await entry.login('guest',false,true);assert.equal(entry.screen,'login');assert.equal(entry.busy,false);assert.deepEqual(calls,['resume']);});
test('required consent and notification choice gate session access',async()=>{const f=fixture();f.items.delete('tapwar-consent-v2');await f.entry.login('guest',false,true);assert.deepEqual(f.calls,[]);f.items.set('tapwar-consent-v2','accepted');f.a.liveOps.push.choice=null;await f.entry.login('guest',false,true);assert.deepEqual(f.calls,[]);});
test('logout saves before signing out and clears remembered login',async()=>{const {entry,calls,items}=fixture();entry.screen='game';await entry.logout();assert.deepEqual(calls,['save','signout']);assert.equal(entry.screen,'title');assert.equal(items.has('tapwar-login-method'),false);assert.equal(items.has('tapwar-consent-v2'),true);});
test('failed logout save preserves authentication and gameplay',async()=>{const {entry,a,calls,items}=fixture();entry.screen='game';a.operations.save=async()=>{throw Error('online.unreachable');};await entry.logout();assert.equal(entry.playing,true);assert.equal(items.get('tapwar-login-method'),'google');assert.deepEqual(calls,['online.unreachable']);});
test('Firebase resume reads existing auth and logout clears connection cache',async()=>{
 const current={uid:'qa-only',isAnonymous:false};const auth={currentUser:current,authStateReady:async()=>{}};let popups=0,creates=0;
 const {FirebaseCloud}=load('assets/scripts/FirebaseCloud.ts',{'cc':{sys:{isNative:false,OS:{ANDROID:'android'}}},'./vendor/firebase-sdk.js':{getApps:()=>[{}],initializeApp:()=>({}),getAuth:()=>auth,getFirestore:()=>({}),signOut:async()=>{auth.currentUser=null;},signInAnonymously:async()=>{creates++;},signInWithPopup:async()=>{popups++;}},'./NativeServices':{},'./FirebaseConfig':{FIREBASE_CONFIG:{}},'./core/LiveOps':{}});
 const c=new FirebaseCloud();assert.equal(await c.resume(),'google');assert.equal(await c.connect(),'qa-only');await c.logout();assert.equal(c.uid,'');assert.equal(await c.resume(),null);assert.equal(creates,0);assert.equal(popups,0);
});
