import { GROWTH_STATS, gemstoneSlots, gemstoneBonus } from './core/Balance';
import type { GameApp } from './GameApp';
import { Expansion } from './core/Expansion';
import { fmt, display } from './core/Amount';
import { t } from './core/I18n';
import { Node, Graphics, Vec3, tween } from 'cc';
export class ExpansionUI {
 constructor(public a:GameApp){}
 get g(){return this.a.game;} get e(){return new Expansion(this.g);} get x(){return this.g.s.extra;}
 tr(k:string,v:Record<string,string|number>={}){return t(this.g.s.locale,k,v);}
 id(k:string){return this.a.id(k);}
 action(fn:()=>boolean,next:()=>void){this.a.act(fn,next);}
 list(title:string,rows:any[],height=680){const p=this.a.open(this.tr(title),height);this.a.scroll(p,0,-25,400,height-120,rows);return p;}
 hub(){this.list('extra.hub',[
 ['money.store',()=>this.a.payments.store()],['money.adPoints',()=>this.a.payments.ads()],['balance.title',()=>this.balance()],['extra.build',()=>this.build()],['extra.talents',()=>this.talents()],['extra.perks',()=>this.perks()],['extra.petPuzzle',()=>this.petPuzzle()],['extra.petMilestones',()=>this.petMilestones()],
 ['extra.dustShop',()=>this.dustShop()],['extra.crystal',()=>this.crystal()],['extra.souls',()=>this.souls()],['extra.gems',()=>this.gems()],['extra.monuments',()=>this.monuments()],
 ['extra.collectibles',()=>this.collectibles()],['inbox.title',()=>this.inbox()],['extra.cosmetics',()=>this.cosmetics()],['extra.notifications',()=>this.notifications()],['extra.export',()=>this.exportSave()],
 ['complete.serverCards',()=>this.serverCards()],['complete.display',()=>this.displaySettings()],['complete.support',()=>this.support()],['complete.account',()=>this.account()],['extra.serviceStatus',()=>this.serviceStatus()],['extra.guildTools',()=>this.guildTools()],['extra.eventModes',()=>this.eventHub()],['extra.limited',()=>this.limited()]
 ].map(([key,fn])=>({title:this.tr(key as string),action:this.tr('action.open'),click:fn})));}
 equipmentDrops(){const items=this.g.s.equipment.filter(e=>this.x.unseenEquipment.includes(e.id));this.list('complete.drops',items.map(item=>({title:this.a.itemName(item),sub:this.tr('action.level',{level:item.level}),action:this.tr('action.details'),click:()=>{this.x.unseenEquipment=this.x.unseenEquipment.filter(id=>id!==item.id);this.g.persist();this.a.item(item);}})));}
 tournaments(){void this.a.remote(async()=>{const boot=await this.a.onlineService.connect(this.tr('online.defaultName')),history=await this.a.onlineService.request('/competition/history');this.list('menu.tournament',[
 {title:this.tr('complete.regular'),sub:this.tr('complete.regularRule'),action:this.tr('action.open'),click:()=>this.tournament(boot.regular.id,'regular')},
 {title:this.tr('online.abyss'),sub:this.tr('online.competitionInfo'),action:this.tr('action.open'),click:()=>this.tournament(boot.tournament.id,'abyss')},
 ...history.filter((r:any)=>Date.now()>=r.end).map((r:any)=>({title:this.tr(r.id<0?'complete.regular':'online.abyss'),sub:this.tr('complete.history',{stage:r.score,date:new Date(r.end).toLocaleDateString(this.g.s.locale)}),action:this.tr(r.claimed?'action.claimed':'action.claim'),click:()=>this.tournament(r.id,r.id<0?'regular':'abyss')}))]);});}
 tournament(id:number,mode:string){void this.a.remote(async()=>{const data=await this.a.onlineService.request('/competition?id='+id),ended=Date.now()>=data.tournament.end;this.a.competitionId=id;const p=this.a.open(this.tr(mode==='regular'?'complete.regular':'online.abyss'),710);this.a.label(p,this.tr(mode==='regular'?'complete.regularRule':'online.competitionInfo'),0,231,375,125,16);this.a.label(p,this.tr('complete.tournamentEnd',{time:new Date(data.tournament.end).toLocaleString(this.g.s.locale)}),0,144,375,45,14);this.a.scroll(p,0,-60,400,335,data.leaderboard.map((r:any,i:number)=>({title:this.tr('online.rank',{rank:i+1,name:r.name}),sub:this.tr('hud.stage',{stage:r.score}),action:this.tr('action.details'),click:()=>this.a.info(r.name,this.tr('complete.rankInfo',{rank:i+1,stage:r.score,reward:Math.max(25,200-i*10)}))})));this.a.button(p,this.tr(ended?(data.claimed?'action.claimed':'action.claim'):(data.state?'online.enter':'online.join')),0,-277,375,50,()=>{void this.a.remote(async()=>{if(ended){const reward=await this.a.onlineService.command('/competition/claim',{id},`tournament-claim-${id}-${this.a.onlineService.accountId}`);this.action(()=>this.applyServerReward(reward),()=>this.a.toast(this.tr('reward.done')));this.a.remoteBusy=false;this.tournament(id,mode);}else{const result=await this.a.onlineService.command('/competition/join',{mode});this.a.competitionId=result.id;this.a.competitionBattle(result.state);}});},true);});}
 serverCards(){void this.a.remote(async()=>{await this.a.onlineService.connect(this.tr('online.defaultName'));const w=await this.a.onlineService.request('/raid/cards'),p=this.a.open(this.tr('complete.serverCards'),720);this.a.label(p,this.tr('complete.serverCardInfo',{dust:w.dust}),0,245,375,90,18);const cycle=Math.floor(Date.now()/21600000),offers=[cycle%18,(cycle+7)%18,(cycle+13)%18];this.a.scroll(p,0,-70,400,460,w.cards.map((level:number,i:number)=>({title:this.tr(`card.${i}`),sub:this.tr('raid.card',{level,fragments:w.fragments[i]}),action:this.tr('action.details'),click:()=>{const box=this.a.open(this.tr(`card.${i}`),520);this.a.label(box,this.tr('complete.cardProc.'+i%3),0,135,375,75,18);this.a.button(box,this.tr('raid.upgrade',{cost:level*10}),0,30,375,50,()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/raid/cards/upgrade',{card:i});this.a.remoteBusy=false;this.serverCards();});},true);if(offers.includes(i))this.a.button(box,this.tr('extra.dustOffer',{dust:w.dust}),0,-60,375,50,()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/raid/cards/buy',{card:i});this.a.remoteBusy=false;this.serverCards();});});this.a.button(box,this.tr('action.back'),0,-160,375,45,()=>this.serverCards());}})));});}
 solo(){
  const r=this.g.raid;this.list('raid.title',[
   {title:this.tr('raid.portal',{portal:this.g.s.portal}),sub:this.tr('raid.desc'),action:this.tr('action.attack'),click:()=>{if(r&&!r.claimed)this.a.raidView();else this.action(()=>this.g.startRaid(),()=>this.a.raidView());}},
   {title:this.tr('complete.portals'),action:this.tr('action.select'),click:()=>this.portals()},
   {title:this.tr('complete.presets'),action:this.tr('action.open'),click:()=>this.presets()},
   {title:this.tr('menu.cards'),action:this.tr('action.open'),click:()=>this.a.cards()},
   {title:this.tr('complete.dailyPortal'),sub:this.tr('complete.dailyPortalInfo',{count:this.x.soloCleared.length}),action:this.tr(this.x.soloRewardDay===this.x.day?'action.claimed':'action.claim'),click:()=>this.action(()=>this.e.dailyPortal(this.id('solo-daily')),()=>this.solo())}
  ]);
 }
 portals(page=0){const top=Math.min(1000,this.g.s.portal),first=page*20+1;const rows:any[]=Array.from({length:Math.min(20,top-first+1)},(_,n)=>{const portal=first+n;return {title:this.tr('raid.portal',{portal}),sub:this.tr(this.x.soloCleared.includes(portal)?'extra.collected':'complete.portalReplay'),action:this.tr('action.attack'),click:()=>this.action(()=>this.g.startRaid(portal),()=>this.a.raidView())};});if(page>0)rows.unshift({title:this.tr('action.back'),action:'‹',click:()=>this.portals(page-1)});if(first+19<top)rows.push({title:this.tr('complete.next'),action:'›',click:()=>this.portals(page+1)});this.list('complete.portals',rows);}
 presets(){this.list('complete.presets',this.x.deckPresets.map((deck,i)=>({title:this.tr('complete.preset',{slot:i+1}),sub:deck.map(c=>this.tr(`card.${c}`)).join(' / '),action:this.tr('action.details'),click:()=>{const p=this.a.open(this.tr('complete.preset',{slot:i+1}),390);this.a.label(p,deck.map(c=>this.tr(`card.${c}`)).join(' / '),0,85,370,80,18);this.a.button(p,this.tr('complete.saveDeck'),0,-5,370,50,()=>this.action(()=>this.e.saveDeck(i,this.id('deck-save')),()=>this.presets()));this.a.button(p,this.tr('action.apply'),0,-90,370,50,()=>this.action(()=>this.e.loadDeck(i,this.id('deck-load')),()=>this.solo()),true);}})));}
 displaySettings(){this.list('complete.display',(['scientific','effects'] as const).map(key=>({title:this.tr('complete.'+key),action:this.tr(this.x[key]?'settings.on':'settings.off'),click:()=>{this.x[key]=!this.x[key];this.g.persist();this.a.draw();this.displaySettings();}})));}
 support(){const p=this.a.open(this.tr('complete.support'),550);this.a.label(p,this.tr('complete.supportInfo'),0,130,375,165,17);this.a.button(p,this.tr('extra.export'),0,-10,375,50,()=>this.exportSave());this.a.button(p,this.tr('complete.import'),0,-90,375,50,()=>this.importSave());this.a.button(p,this.tr('extra.serviceStatus'),0,-170,375,50,()=>this.serviceStatus());this.a.button(p,this.tr('complete.restoreBackup'),0,-233,375,44,()=>this.restoreBackup());}
 restoreBackup(){const raw=this.g.storage?.getItem('ember-ascent-before-restore');if(!raw){this.a.toast(this.tr('error.locked'));return;}try{const state=JSON.parse(raw);this.g.migrate(state);this.g.validate(state);this.a.confirm(this.tr('complete.restoreBackup'),this.tr('complete.replaceSave'),()=>this.action(()=>this.restore(state),()=>{this.a.close();this.a.draw();}));}catch{this.a.toast(this.tr('error.save'));}}
 importSave(){if(typeof document==='undefined'){this.a.toast(this.tr('extra.browserOnly'));return;}const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const file=input.files?.[0];if(!file)return;if(file.size>1000000){this.a.toast(this.tr('error.invalid'));return;}void file.text().then(raw=>{try{const state=JSON.parse(raw);this.g.migrate(state);this.g.validate(state);this.a.confirm(this.tr('complete.import'),this.tr('complete.replaceSave'),()=>this.action(()=>this.restore(state),()=>{this.a.close();this.a.draw();}));}catch{this.a.toast(this.tr('error.save'));}}).catch(()=>this.a.toast(this.tr('error.save')));};input.click();}
 restore(state:any):boolean{const before=this.g.s;try{this.g.migrate(state);this.g.validate(state);this.g.storage?.setItem('ember-ascent-before-restore',JSON.stringify(before));this.g.s=state;this.g.s.lastSeen=this.g.now();if(!this.g.persist())throw Error('error.storage');this.g.revision++;return true;}catch{this.g.s=before;this.g.notice='error.save';return false;}}
 account(){void this.a.remote(async()=>{const boot=await this.a.onlineService.connect(this.tr('online.defaultName')),cloud=await this.a.onlineService.request('/account/save');this.list('complete.account',[
 {title:boot.profile.name,sub:this.a.onlineService.accountId,action:this.tr('complete.rename'),click:()=>this.renameAccount()},
 {title:this.tr('complete.cloudSave'),sub:this.tr('complete.cloudInfo',{version:cloud.version}),action:this.tr('settings.saveButton'),click:()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/account/save',{version:cloud.version,state:this.g.s});this.a.remoteBusy=false;this.account();});}},
 {title:this.tr('complete.cloudLoad'),action:this.tr('action.apply'),click:()=>{if(!cloud.state){this.a.toast(this.tr('error.locked'));return;}this.a.confirm(this.tr('complete.cloudLoad'),this.tr('complete.replaceSave'),()=>this.action(()=>this.restore(cloud.state),()=>{this.a.close();this.a.draw();}));}},
 {title:this.tr('complete.recoveryExport'),sub:this.tr('complete.privateKey'),action:this.tr('complete.exportFile'),click:()=>this.downloadRecovery()},
 {title:this.tr('complete.recoveryImport'),action:this.tr('action.apply'),click:()=>this.importRecovery()}
 ]);});}
 renameAccount(){const p=this.a.open(this.tr('complete.rename'),340),field=this.a.edit(p,0,35,370,48,this.tr('online.defaultName'));field.maxLength=24;this.a.button(p,this.tr('action.apply'),0,-70,370,50,()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/account/name',{name:field.string});this.a.remoteBusy=false;this.account();});},true);}
 downloadRecovery(){if(typeof document==='undefined')return;const o=this.a.onlineService,blob=new Blob([JSON.stringify({version:1,accountId:o.accountId,token:o.token})],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='ember-account-private.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 importRecovery(){if(typeof document==='undefined')return;const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=()=>{const f=input.files?.[0];if(!f||f.size>4096)return;void f.text().then(raw=>{let data:any;try{data=JSON.parse(raw);if(!/^[a-f0-9]{64}$/.test(data.token)||!/^[a-f0-9]{24}$/.test(data.accountId))throw Error();}catch{this.a.toast(this.tr('error.invalid'));return;}this.a.confirm(this.tr('complete.recoveryImport'),this.tr('complete.switchAccount'),()=>{void this.a.remote(async()=>{await this.a.onlineService.recover(data.token,data.accountId);this.a.remoteBusy=false;this.account();});});});};input.click();}
 balance(){this.list('balance.title',[{title:this.tr('balance.scope'),sub:this.tr('balance.scopeInfo')},...GROWTH_STATS.flatMap(stat=>this.g.growthContributions(stat).map(row=>({title:this.tr('balance.stat.'+stat)+' · '+this.tr('balance.source.'+row.source),sub:this.tr('balance.factor',{value:this.a.format(row.log)})})))]);}
 build(){const s=this.g.s;this.list('extra.build',Array.from({length:6},(_,i)=>({title:this.tr(`branch.${i}`),sub:this.tr('extra.buildRow',{levels:s.skills.slice(i*3,i*3+3).join(' / '),damage:this.a.format(this.g.tapDamage())}),action:this.tr('action.details'),click:()=>this.a.skills()})));}
 talents(){this.list('extra.talents',[
 {title:this.tr('extra.mastery'),sub:this.tr('extra.talentValue',{value:this.g.s.weapons.reduce((a,b)=>a+b,0)+this.g.s.scrolls.reduce((a,b)=>a+b,0)})},
 {title:this.tr('extra.crafting'),sub:this.tr('extra.talentValue',{value:this.g.s.crafted})},
 {title:this.tr('extra.petMilestones'),sub:this.tr('extra.talentValue',{value:this.g.s.pets.reduce((a,b)=>a+b,0)})},
 {title:this.tr('extra.ascensions'),sub:this.tr('extra.talentValue',{value:this.x.ascensions.reduce((a,b)=>a+b,0)})}]);}
 perks(){this.list('extra.perks',[{title:this.tr('money.ad.mega_boost'),sub:this.tr('money.adReward.mega_boost'),action:this.tr('money.watch'),click:()=>this.a.payments.ads('boost')},...this.x.perkSlots.map((id,slot)=>({title:this.tr('extra.perk',{id:id+1}),sub:this.tr('extra.owned',{count:this.e.perkCount(id)}),icon:id,action:this.tr('action.details'),click:()=>this.perk(slot)}))]);}
 perk(slot:number){const id=this.x.perkSlots[slot],p=this.a.open(this.tr('extra.perk',{id:id+1}),420);this.a.label(p,this.tr('perks.info'),0,70,370,90,18);this.a.button(p,this.tr('action.apply'),0,-12,360,50,()=>this.action(()=>this.e.usePerk(slot,this.id('perk')),()=>this.perks()),true);this.a.button(p,this.tr('extra.replace'),0,-90,360,50,()=>this.list('extra.perks',Array.from({length:10},(_,i)=>({title:this.tr('extra.perk',{id:i+1}),sub:this.tr('extra.owned',{count:this.e.perkCount(i)}),action:this.tr('action.select'),click:()=>this.a.confirm(this.tr('extra.replace'),this.tr('extra.perkWarning'),()=>this.action(()=>this.e.swapPerk(slot,i,this.id('perk-swap')),()=>this.perks()))}))));}
 hero(i:number){const p=this.a.open(this.tr(`hero.${i}`),540);this.a.label(p,this.tr('extra.heroStats',{level:this.g.s.run.heroes[i],ascensions:this.x.ascensions[i],skills:this.x.heroSkills[i],weapons:this.g.s.weapons[i],scrolls:this.g.s.scrolls[i]}),0,110,375,160,19);this.a.button(p,this.tr('extra.heroSkill'),0,-15,370,50,()=>this.action(()=>this.e.heroSkill(i,this.id('hero-skill')),()=>this.hero(i)),true);this.a.button(p,this.tr('extra.ascend'),0,-90,370,50,()=>this.a.confirm(this.tr('extra.ascend'),this.tr('extra.ascendInfo'),()=>this.action(()=>this.e.ascend(i,this.id('ascend')),()=>this.hero(i))));this.a.label(p,this.tr('complete.heroSkillInfo',{level:[10,25,50,100,200,400,800][this.x.heroSkills[i]]||800,damage:this.a.format(this.g.heroDamage(i))}),0,-184,370,80,14);}
 petDetail(i:number){const p=this.a.open(this.tr(`pet.${i}`),500);this.a.label(p,this.tr('complete.petDetail',{level:this.g.s.pets[i],active:(1+this.g.s.pets[i]*.025).toFixed(2),passive:(1+this.g.s.pets[i]*.025*Math.min(1,this.g.s.pets[i]/100)).toFixed(2)}),0,115,375,120,18);this.a.button(p,this.tr('action.equip'),0,10,375,50,()=>{if(!this.g.s.pets[i])this.a.toast(this.tr('error.locked'));else{this.g.s.activePet=i;this.g.persist();this.a.close();this.a.drawPanel();}},true);this.a.button(p,this.tr('extra.petPuzzle'),0,-65,375,50,()=>this.petPuzzle());this.a.button(p,this.tr('extra.petMilestones'),0,-140,375,50,()=>this.petMilestones());}
 petPuzzle(){const p=this.a.open(this.tr('extra.petPuzzle'),660);this.a.label(p,this.tr('extra.puzzleInfo',{energy:this.x.petEnergy,matches:this.x.petMatched.length/2}),0,234,375,100,17);for(let i=0;i<16;i++){const visible=this.x.petMatched.includes(i)||this.x.petFace.includes(i);this.a.button(p,visible?String(this.x.petBoard[i]+1):'?',-147+i%4*98,113-Math.floor(i/4)*87,88,75,()=>this.action(()=>this.e.petTile(i,this.id('pet-tile')),()=>this.petPuzzle()),visible);}this.a.label(p,this.tr('extra.puzzleReward'),0,-253,375,58,16);}
 petMilestones(){this.list('extra.petMilestones',[10,25,50,100,250,500,1000].map(target=>({title:this.tr('extra.petTarget',{target}),action:this.tr(this.x.petMilestones.includes(target)?'action.claimed':'action.claim'),click:()=>this.action(()=>this.e.petMilestone(target,this.id('pet-milestone')),()=>this.petMilestones())})));}
 dustShop(){this.list('extra.dustShop',this.e.dustOffers().map(i=>({title:this.tr(`card.${i}`),sub:this.tr('extra.dustOffer',{dust:this.g.s.dust}),icon:i,action:this.tr('action.buy'),click:()=>this.action(()=>this.e.dustBuy(i,this.id('dust')),()=>this.dustShop())})));}
 crystal(){this.list('extra.crystal',[0,1,2].map(slot=>({title:this.tr('extra.crystalSlot',{slot:slot+1}),sub:this.tr('extra.crystalRule',{level:this.g.s.cards.reduce((a,b)=>a+b,0)}),action:this.tr('action.select'),click:()=>this.list('extra.crystal',this.g.s.cards.map((level,i)=>({level,i})).filter(c=>c.i%3===slot).map(c=>({title:this.tr(`card.${c.i}`),sub:this.tr('extra.cardBoost',{base:c.level,effective:this.e.boostedLevel(c.i)}),action:this.tr('action.select'),click:()=>this.action(()=>this.e.crystal(slot,c.i,this.id('crystal')),()=>this.crystal())})))})));}
 souls(){const p=this.a.open(this.tr('extra.souls'),720);this.a.label(p,this.tr('extra.soulSummary',{souls:this.g.s.souls,level:Math.floor(this.x.summonCount/10)+1,points:Math.floor(this.x.summonCount/5),banner:this.x.banner}),0,255,380,76,17);this.a.button(p,this.tr('extra.banner'),-137,185,126,42,()=>{this.x.banner=(this.x.banner+1)%7;this.g.persist();this.souls();});[1,10].forEach((count,i)=>this.a.button(p,this.tr('extra.summon',{count}),i?137:0,185,126,42,()=>this.summonConfirm(count),true));this.a.button(p,this.tr('extra.levelAll'),-101,130,190,42,()=>this.action(()=>this.e.levelTitans(Array.from({length:120},(_,i)=>i),this.id('level-all')),()=>this.souls()));this.a.button(p,this.tr('meta.research'),101,130,190,42,()=>this.a.research());this.a.scroll(p,0,-103,400,405,this.g.s.titans.map((copies,i)=>({title:this.tr('extra.titan',{id:i+1}),sub:this.tr('extra.titanStats',{copies,level:this.x.titanLevels[i],cost:this.e.titanCost(i)}),action:this.tr('action.details'),click:()=>this.titan(i)})));}
 titan(i:number){const p=this.a.open(this.tr('extra.titan',{id:i+1}),420);this.a.label(p,this.tr('extra.titanStats',{copies:this.g.s.titans[i],level:this.x.titanLevels[i],cost:this.e.titanCost(i)}),0,50,375,130,21);this.a.button(p,this.tr('action.upgrade'),0,-112,370,50,()=>this.action(()=>this.e.levelTitans([i],this.id('titan')),()=>this.titan(i)),true);}
 gems(){const p=this.a.open(this.tr('extra.gems'),700);this.a.button(p,this.tr('meta.crack'),-101,248,190,50,()=>this.crackResult(),true);this.a.button(p,this.tr('extra.mysticResearch'),101,248,190,50,()=>this.mystic());this.a.scroll(p,0,-55,400,520,this.g.s.stones.map((level,i)=>({title:this.tr('meta.stone',{index:i+1,level}),sub:this.tr('extra.rarity',{rarity:this.e.gemstoneRarity(i)}),icon:i,action:this.tr('action.details'),click:()=>this.gem(i)})));}
 gem(i:number){const p=this.a.open(this.tr('meta.stone',{index:i+1,level:this.g.s.stones[i]}),660);this.a.label(p,this.tr('extra.gemInfo',{rarity:this.e.gemstoneRarity(i),bonus:gemstoneSlots(this.g.s.stones[i])}),0,220,380,100,18);this.a.scroll(p,0,-68,400,400,[...GROWTH_STATS.map(stat=>({title:this.tr('balance.stat.'+stat),sub:this.tr('balance.factor',{value:this.a.format(gemstoneBonus(i,this.g.s.stones[i],stat))})})),...[100,200,400,500].map(level=>({title:this.tr('action.level',{level}),action:this.tr(this.x.gemMilestones.includes(`${i}:${level}`)?'action.claimed':'action.claim'),click:()=>this.action(()=>this.e.gemMilestone(i,level,this.id('gem-milestone')),()=>this.gem(i))}))]);}
 mystic(){this.list('extra.mysticResearch',this.x.mysticResearch.map((level,i)=>({title:this.tr('meta.researchNode',{index:i+1,level}),sub:this.tr('extra.researchPoints',{points:this.x.geodesOpened-this.x.mysticResearch.reduce((a,l)=>a+l*(l+1)/2,0)}),action:this.tr('action.upgrade'),click:()=>this.action(()=>this.e.mysticNode(i,this.id('mystic')),()=>this.mystic())})));}
 monuments(){this.list('extra.monuments',[{title:this.tr('complete.discoverMonument'),sub:this.tr('complete.monumentCost',{cost:this.a.format(Math.log10(Math.pow(2,this.g.s.monuments.filter(Boolean).length)))}),action:this.tr('action.apply'),click:()=>{const before=this.g.s.monuments.slice();this.action(()=>this.e.discoverMonument(this.id('monument-discover')),()=>this.monument(this.g.s.monuments.findIndex((l,i)=>l>before[i])));}},...this.g.s.monuments.map((level,i)=>({title:this.tr('meta.monument',{index:i+1,level}),sub:this.tr('extra.enchanted',{value:this.x.monumentEnchanted[i]}),action:this.tr('action.details'),click:()=>this.monument(i)}))]);}
 monument(i:number){const p=this.a.open(this.tr('meta.monument',{index:i+1,level:this.g.s.monuments[i]}),530);this.a.label(p,this.tr('meta.monumentInfo',{value:this.a.format(this.g.s.mementos)}),0,140,380,85,20);this.a.button(p,this.tr('action.upgrade'),0,50,375,50,()=>this.action(()=>this.g.monument(i,this.id('monument')),()=>this.monument(i)),true);this.a.button(p,this.tr('artifact.salvage'),0,-25,375,50,()=>this.a.confirm(this.tr('artifact.salvage'),this.tr('extra.monumentRefund'),()=>this.action(()=>this.e.salvageMonument(i,this.id('monument-salvage')),()=>this.monuments())));this.a.button(p,this.tr('extra.enchantChoices'),0,-100,375,50,()=>this.list('extra.enchantChoices',this.e.enchantCandidates().map(id=>({title:this.tr('meta.monument',{index:id+1,level:this.g.s.monuments[id]}),action:this.tr('action.apply'),click:()=>this.action(()=>this.e.enchantMonument(id,this.id('monument-enchant')),()=>this.monuments())}))));this.a.button(p,this.tr('extra.seasonRewards'),0,-180,375,50,()=>this.inbox());}
 collectibles(){this.list('extra.collectibles',[0,1,2].map(i=>({title:this.tr(`extra.collectible.${i}`),sub:this.tr('daily.progress',{current:[this.x.dailyFairies,this.x.dailyEquipment,this.x.dailyEggs][i],goal:[3,3,1][i]}),action:this.tr(this.x.collectionClaims.includes(String(i))?'action.claimed':'action.claim'),click:()=>this.action(()=>this.e.collectible(i,this.id('collectible')),()=>this.collectibles())})));}
 inbox(){this.list('inbox.title',this.x.mails.map(m=>({title:this.tr(m.title),sub:this.tr('extra.mailReward',{gems:m.gems,shards:m.shards}),action:this.tr('action.details'),click:()=>{const p=this.a.open(this.tr(m.title),430);this.a.label(p,this.tr('extra.mailReward',{gems:m.gems,shards:m.shards}),0, 70,375,80,22);this.a.button(p,this.tr(m.claimed?'action.claimed':'action.claim'),0,-10,370,50,()=>this.action(()=>this.e.claimMail(m.id,this.id('mail')),()=>this.inbox()),true);this.a.button(p,this.tr('extra.delete'),0,- 90,370,50,()=>this.action(()=>this.e.deleteMail(m.id,this.id('delete-mail')),()=>this.inbox()));}})));}
 cosmetics(slot=0){const p=this.a.open(this.tr('extra.cosmetics'),600);[0,1,2].forEach(i=>this.a.button(p,this.tr(`extra.cosmetic.${i}`),-133+i*133,211,124,42,()=>this.cosmetics(i),i===slot));this.a.scroll(p,0,-50,400,430,Array.from({length:6},(_,i)=>({title:this.tr('extra.style',{id:i+1}),sub:this.tr('hero.locked',{stage:i*50}),icon:i,action:this.tr(this.x.cosmetics[slot]===i?'action.selected':'action.apply'),click:()=>this.action(()=>this.e.cosmetic(slot,i,this.id('cosmetic')),()=>{this.a.close();this.a.draw();this.cosmetics(slot);})})));}
 notifications(){this.list('extra.notifications',[0,1,5].map(i=>({title:this.tr(`extra.notice.${i}`),action:this.tr(this.x.notifications[i]?'settings.on':'settings.off'),click:()=>{this.x.notifications[i]=!this.x.notifications[i];this.g.persist();if(this.x.notifications[i]&&typeof Notification!=='undefined'&&Notification.permission==='default')void Notification.requestPermission();this.notifications();}})));}
 exportSave(){if(typeof document==='undefined'){this.a.toast(this.tr('extra.browserOnly'));return;}const blob=new Blob([JSON.stringify(this.g.s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='ember-ascent-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.a.toast(this.tr('settings.save'));}
 eventHub(){this.list('extra.eventModes',[
 ['complete.eventRules',()=>this.a.info(this.tr('complete.eventRules'),this.tr('complete.eventRulesBody',{time:new Date((this.x.eventSeason+1)*28*86400000).toLocaleString(this.g.s.locale),tokens:this.x.eventEarned}))],['extra.eventShop',()=>this.eventShop()],['extra.alchemy',()=>this.alchemy()],['extra.drop',()=>this.drop()],['extra.tower',()=>this.tower()],['event.path',()=>this.a.events()],['extra.seasonRewards',()=>this.inbox()],['extra.globalRaid',()=>this.a.globalRaid()],['extra.eventRanks',()=>this.a.eventRanks()]
 ].map(([key,fn])=>({title:this.tr(key as string),action:this.tr('action.open'),click:fn})));}
 eventShop(){this.list('extra.eventShop',[0,1,2].map(i=>({title:this.tr(['extra.eventShards','shop.pet','meta.crack'][i]),sub:this.tr('extra.tokenCost',{count:[50,100,75][i]}),action:this.tr('action.buy'),click:()=>this.action(()=>this.e.eventShop(i,this.id('event-shop')),()=>this.eventShop())})));}
 alchemy(a=0,b=0){const p=this.a.open(this.tr('extra.alchemy'),490);this.a.label(p,this.tr('extra.alchemyInfo',{count:this.x.recipes.length,tokens:this.g.s.eventTokens}),0,135,375,100,18);this.a.button(p,this.tr('extra.ingredient',{id:a+1}),-99, 30,184,75,()=>this.alchemy((a+1)%4,b));this.a.button(p,this.tr('extra.ingredient',{id:b+1}),99, 30,184,75,()=>this.alchemy(a,(b+1)%4));this.a.button(p,this.tr('extra.combine'),0,-100,375, 50,()=>this.action(()=>this.e.alchemy(a,b,this.id('alchemy')),()=>this.alchemy(a,b)),true);}
 drop(){const p=this.a.open(this.tr('extra.drop'),680);this.a.label(p,this.tr('extra.tokenCost',{count:25}),0,250,375, 40,19);for(let row=0;row<8;row++)for(let col=0;col<=row;col++)this.a.rect(p,(col-row/2)*35,175-row*40,5,5,'#a3b7bb');this.a.button(p,this.tr('extra.dropBall'),0,-250,375, 50,()=>{if(this.e.drop(this.id('drop'))){const ball=this.a.rect(p,0,207,12,12,'#ecc071');let right=0,anim=tween(ball);this.x.dropHistory.forEach((bit,row)=>{right+=bit;anim=anim.to(.13,{position:new Vec3((right-(row+1)/2)*35,175-row*40,0)});});anim.call(()=>this.a.toast(this.tr('reward.done'))).start();}else this.a.flushNotice();},true);}
 tower(){const p=this.a.open(this.tr('extra.tower'),490);this.a.label(p,this.tr('extra.towerInfo',{floor:this.x.towerFloor,keys:this.x.towerKeys}),0,135,375,100,22);for(let i=0;i<3;i++)this.a.button(p,this.tr('extra.door',{id:i+1}),-132+i*132,-5,120,150,()=>this.action(()=>this.e.tower(i,this.id('tower')),()=>this.tower()),true);}



 applyServerReward(r:any):boolean{return this.g.transaction(r.claimId,()=>{this.g.require(!this.g.s.claims.includes(r.claimId),'error.claimed');this.g.s.claims.push(r.claimId);this.g.s.gems+=r.gems;this.g.s.shards+=r.shards;});}
 heroMastery(scrolls=false){const levels=scrolls?this.g.s.scrolls:this.g.s.weapons,p=this.a.open(this.tr('hero.mastery'),700);this.a.button(p,this.tr('extra.weapons'),-101,247,190,45,()=>this.heroMastery(false),!scrolls);this.a.button(p,this.tr('extra.scrolls'),101,247,190,45,()=>this.heroMastery(true),scrolls);this.a.label(p,this.tr('extra.masterySets',{sets:Math.min(...levels)}),0,186,375,50,17);this.a.scroll(p,0,-83,400,460,levels.map((level,i)=>({title:this.tr(`hero.${i}`),sub:this.tr('action.level',{level}),icon:i,action:this.tr('action.details'),click:()=>this.hero(i)})));}
 equipmentSets(){const p=this.a.open(this.tr('equipment.sets'),700);this.a.label(p,this.tr('extra.craftPower',{spent:this.g.s.crafted,power:(1+this.g.s.crafted*.001).toFixed(2)}),0,245,375,75,18);this.a.scroll(p,0,-55,400,500,Array.from({length:Math.max(12,Math.max(0,...this.g.s.setHistory.map(p=>Math.floor(p/5)))+2)},(_,i)=>({title:this.tr('extra.set',{id:i+1}),sub:this.tr('daily.progress',{current:this.g.s.setHistory.filter(part=>Math.floor(part/5)===i).length,goal:5}),action:this.tr('action.details'),click:()=>this.equipmentSet(i)})));}
 equipmentSet(i:number){this.list('extra.setDetails',Array.from({length:5},(_,slot)=>({title:this.tr(`slot.${slot}`),sub:this.tr(this.g.s.setHistory.includes(i*5+slot)?'extra.collected':'extra.missing'),icon:slot,action:this.tr('equipment.craft'),click:()=>this.a.confirm(this.tr('equipment.craft'),this.tr('complete.craftPart',{cost:this.g.craftCost(i,slot)}),()=>this.action(()=>this.g.craft(this.id('craft-part'),i,slot),()=>this.equipmentSet(i)))})));}
 summonConfirm(count:number){this.a.confirm(this.tr('extra.summon',{count}),this.tr('extra.summonCost',{count:count*10}),()=>{const before=this.g.s.titans.slice();this.action(()=>this.e.summon(count,this.x.banner,this.id('summon')),()=>this.list('extra.summonResult',this.g.s.titans.map((value,i)=>({value:value-before[i],i})).filter(v=>v.value>0).map(v=>({title:this.tr('extra.titan',{id:v.i+1}),sub:this.tr('extra.owned',{count:v.value}),action:this.tr('action.details'),click:()=>this.titan(v.i)}))));});}
 crackResult(){const before=this.g.s.stones.slice();this.action(()=>this.g.crack(this.id('geode')),()=>this.gem(this.g.s.stones.findIndex((value,i)=>value>before[i])));}
 notifyReady(){if(typeof Notification==='undefined'||Notification.permission!=='granted'||typeof document==='undefined'||!document.hidden)return;const day=Math.floor(this.g.now()/86400000);const ready=[this.g.now()>=this.g.s.eggAt,!this.g.s.claims.includes('daily.0'),false,false,false,this.x.mails.some(m=>!m.claimed&&m.expires>this.g.now())];ready.forEach((yes,i)=>{const key=`notice.${day}.${i}`;if(yes&&this.x.notifications[i]&&!this.g.s.claims.includes(key)){new Notification(this.tr('game.name'),{body:this.tr(`extra.notice.${i}`)});this.g.s.claims.push(key);}});}
 serviceStatus(){void this.a.remote(async()=>{const health=await this.a.onlineService.request('/health');this.a.info(this.tr('extra.serviceStatus'),this.tr(health.maintenance?'extra.maintenance':'extra.serviceReady',{version:health.version||'0.2.0'}));});}

 guildBattle(){void this.a.remote(async()=>{let r=await this.a.onlineService.request('/guild/raid');if(!r)r=await this.a.onlineService.command('/guild/raid/start',{deck:this.g.s.deck});this.guildBattlePanel(r);});}
 guildBattlePanel(data:any){const p=this.a.open(this.tr('online.guildRaid'),700),r=data.raid,start=Date.now(),status=this.a.label(p,'',0,250,375,55,20);for(let i=0;i<8;i++)this.a.button(p,this.tr('raid.part',{part:i+1})+'\n'+display(r.hp[i]),i%2?94:-94,160-Math.floor(i/2)*80,175,65,()=>{void this.a.remote(async()=>{const next=await this.a.onlineService.command('/guild/raid/hit',{id:data.id,part:i});this.guildBattlePanel(next);});});this.a.label(p,this.tr('extra.guildDeckInfo'),0,-172,375,64,14);this.a.button(p,this.tr('extra.raidSubmit'),0,-260,375,52,()=>{void this.a.remote(async()=>{const result=await this.a.onlineService.command('/guild/raid/finish',{id:data.id},'raid-finish-'+data.id);this.a.info(this.tr('raid.result'),this.tr('extra.raidSummary',{damage:result.damage,hp:result.hp,cards:result.cardDamage.map((n:number)=>display(n)).join(' / ')}));});},true);this.a.modalRefresh=()=>{status.string=this.tr('raid.damage',{damage:display(r.damage),seconds:Math.max(0,Math.ceil(r.seconds-(Date.now()-start)/1000))});};this.a.modalRefresh();}
 guildTools(){this.list('extra.guildTools',[
 ['complete.guildInfo',()=>this.guildInfo()],['extra.guildSearch',()=>this.guildSearch()],['extra.guildEdit',()=>this.guildEdit()],['extra.stickers',()=>this.stickers()],['extra.guildLogs',()=>this.guildLogs()],['extra.guildVault',()=>this.vault()],['extra.retire',()=>this.retire()]
 ].map(([key,fn])=>({title:this.tr(key as string),action:this.tr('action.open'),click:fn})));}
 joinGuild(id:string,name:string){this.a.confirm(this.tr('online.join'),this.tr('complete.joinGuild',{name}),()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/guild/join',{guild:id});this.a.remoteBusy=false;this.a.guild();});});}
 guildInfo(){void this.a.remote(async()=>{const data=await this.a.onlineService.request('/guild'),info=await this.a.onlineService.request('/guild/info');this.a.info(data.guild.name,this.tr('complete.guildInfoBody',{count:data.members.length,description:info.settings.description||this.tr('complete.noDescription'),damage:info.vault}));});}
 guildSearch(){const p=this.a.open(this.tr('extra.guildSearch'),680),field=this.a.edit(p,0,225,375,48,this.tr('online.guildName'));this.a.button(p,this.tr('extra.search'),0,150,375,48,()=>{const q=field.string;void this.a.remote(async()=>{await this.a.onlineService.connect(this.tr('online.defaultName'));const rows=await this.a.onlineService.request('/guilds?q='+encodeURIComponent(q));this.list('extra.guildSearch',rows.map((r:any)=>({title:r.name,sub:this.tr('online.members',{count:r.members}),action:this.tr('online.join'),click:()=>this.joinGuild(r.id,r.name)})));});});}
 guildEdit(){void this.a.remote(async()=>{const data=await this.a.onlineService.request('/guild'),info=await this.a.onlineService.request('/guild/info'),p=this.a.open(this.tr('extra.guildEdit'),590),name=this.a.edit(p,0,170,375,48,this.tr('online.guildName')),desc=this.a.edit(p,0,60,375,70,this.tr('extra.description'));name.string=data.guild.name;desc.string=info.settings.description;this.a.button(p,this.tr('action.apply'),0,-130,375,50,()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/guild/edit',{name:name.string,description:desc.string,badge:info.settings.badge});this.a.remoteBusy=false;this.a.guild();});},true);});}
 stickers(){this.list('extra.stickers',Array.from({length:6},(_,i)=>({title:this.tr(`extra.sticker.${i}`),action:this.tr('online.send'),click:()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/guild/chat',{body:`[sticker:${i}]`});this.a.remoteBusy=false;this.a.guild();});}})));}
 guildLogs(){void this.a.remote(async()=>{const info=await this.a.onlineService.request('/guild/info');this.list('extra.guildLogs',info.logs.map((r:any)=>({title:r.name,sub:this.tr('extra.contribution',{value:r.damage})})));});}
 vault(){void this.a.remote(async()=>{const info=await this.a.onlineService.request('/guild/info'),p=this.a.open(this.tr('extra.guildVault'),440);this.a.label(p,this.tr('extra.vaultInfo',{damage:info.vault}),0,70,375,140,19);this.a.button(p,this.tr('action.claim'),0,-100,375,50,()=>{void this.a.remote(async()=>{const r=await this.a.onlineService.command('/guild/vault',{},`vault-${Math.floor(Date.now()/43200000)}-${this.a.onlineService.accountId}`);this.action(()=>this.applyServerReward(r),()=>this.a.close());});},true);});}
 retire(){this.a.confirm(this.tr('extra.retire'),this.tr('extra.retireInfo'),()=>{void this.a.remote(async()=>{await this.a.onlineService.command('/guild/retire');this.a.remoteBusy=false;this.a.guild();});});}
 member(id:string){void this.a.remote(async()=>{const r=await this.a.onlineService.request('/guild/member?id='+encodeURIComponent(id)),p=this.a.open(r.name,420);this.a.label(p,this.tr('extra.contribution',{value:r.damage}),0,50,375,90,22);this.a.label(p,this.tr(r.role==='leader'?'online.leader':'online.member'),0,-50,375,50,20);});}
 limited(){const day=Math.floor(this.g.now()/86400000);this.list('extra.limited',[{title:this.tr('extra.limitedOffer'),sub:this.tr('extra.limitedInfo'),action:this.tr(this.g.s.claims.includes('daily.limited')?'action.claimed':'action.buy'),click:()=>this.action(()=>this.g.transaction(`limited-${day}`,()=>{this.g.require(!this.g.s.claims.includes('daily.limited'),'error.claimed');this.g.require(this.g.s.gems>=100);this.g.s.claims.push('daily.limited');this.g.s.gems-=100;this.g.s.shards+=20;this.e.fortune(10);}),()=>this.limited())}]);}
}
