import {sys,Mask,ScrollView,UITransform,Label} from 'cc';
import type {GameApp} from './GameApp';
import {localized,MailView} from './core/Operations';
import {ZERO} from './core/Amount';
import {PushNotifications} from './PushNotifications';
import {APP_VERSION,STORE_VERSION,Policy,Notice,Platform,validatePolicy,requiresUpdate,mailExpiry,compareVersions} from './core/LiveOps';
export class LiveOpsUI {
 policy:Policy|null=null; blocked=false; checking=false; elapsed=0; error=false;
 constructor(private a:GameApp){}
 get platform():Platform{return sys.os===sys.OS.ANDROID?'android':sys.os===sys.OS.IOS?'ios':'web';}
 push=new PushNotifications(); pushClock=0; opened='';
 get version(){return this.platform==='web'?APP_VERSION:STORE_VERSION;}
 async initialize(){if(this.a.entry.playing)await this.refresh();}
 async refresh(){if(this.checking)return;this.checking=true;try{
  this.policy=await this.a.operations.policy();this.error=false;
  if(requiresUpdate(this.policy,this.platform,this.version)){if(!this.blocked){this.a.close();this.updatePanel();}return;}
  if(this.blocked){this.blocked=false;this.a.close();}
  if(!this.a.operations.ready||this.a.operations.conflict){await this.a.operations.start();void this.a.operations.flushErrors();}
 }catch(e){this.error=true;this.a.operations.report('operations.refresh',e);if(!this.blocked){this.a.close();const a=this.a,p=a.open(a.tr('ops.connectTitle'),430,false);this.blocked=true;a.label(p,a.tr((e as Error).message==='online.saveConflict'?'online.saveConflict':'ops.connectBody'),0,30,370,170,18);a.button(p,a.tr('live.5'),0,-120,360,48,()=>{this.blocked=false;a.close();void this.refresh();},true);}}
 finally{this.checking=false;}}
 tick(dt:number){this.elapsed+=dt;this.pushClock+=dt;if(this.push.supported&&this.a.operations.ready&&this.pushClock>5){this.pushClock=0;void this.push.opened().then(id=>{if(id)this.opened=id;}).catch(()=>{});}if(!this.blocked)this.a.operations.tick(dt);if(this.elapsed>=60){this.elapsed=0;void this.refresh();}
  if(!this.blocked&&this.a.operations.ready&&this.a.operations.conflict){this.a.close();const p=this.a.open(this.a.tr('ops.conflictTitle'),430,false);this.blocked=true;this.a.label(p,this.a.tr('online.saveConflict'),0,30,370,160,18);this.a.button(p,this.a.tr('live.5'),0,-120,360,48,()=>{this.blocked=false;this.a.close();void this.refresh();});return;}
  if(!this.a.modal&&!this.blocked&&this.a.operations.ready){const n=this.opened?this.policy?.notices.find(n=>n.id===this.opened&&!this.a.operations.reads.includes(n.id)):this.policy?.notices.find(n=>!this.a.operations.reads.includes(n.id));this.opened='';if(n){this.notice(n);return;}
   if(this.a.game.s.offline>ZERO)this.a.offline();
  }}
 pushPrompt(){const a=this.a,p=a.open(a.tr('ops.pushTitle'),430);a.label(p,a.tr('ops.pushBody'),0,40,370,190,18);a.button(p,a.tr('ops.pushDecline'),-95,-115,178,48,()=>{void this.push.set(false,a.game.s.locale);a.close();});a.button(p,a.tr('ops.pushAllow'),95,-115,178,48,()=>{void this.push.set(true,a.game.s.locale).then(()=>a.close()).catch(()=>a.toast(a.tr('online.unreachable')));},true);}
 notifications(){const a=this.a;void a.remote(async()=>{const state=await this.push.status(),p=a.open(a.tr('extra.notifications'),480);a.label(p,a.tr(!this.push.supported?'ops.pushUnsupported':state.status==='enabled'?'ops.pushEnabled':'ops.pushDisabled'),0,110,370,120,18);a.button(p,a.tr('ops.pushAllow'),-95,-30,178,48,()=>{void this.push.set(true,a.game.s.locale).then(()=>this.notifications());},true);a.button(p,a.tr('settings.off'),95,-30,178,48,()=>{void this.push.set(false,a.game.s.locale).then(()=>this.notifications());});if(this.push.supported)a.button(p,a.tr('ops.osSettings'),0,-110,370,48,()=>void this.push.settings());});}
 body(p:any,body:string){const a=this.a,view=a.nodeAt(p,'message-scroll',0,5,380,420);view.addComponent(Mask);const h=Math.max(420,body.split('\n').reduce((sum,line)=>sum+Math.max(1,Math.ceil(line.length/20)),0)*27+30),content=a.nodeAt(view,'content',0,210,380,h);content.getComponent(UITransform)!.setAnchorPoint(.5,1);const label=a.label(content,body,0,-h/2,364,h,18);label.overflow=Label.Overflow.CLAMP;label.verticalAlign=Label.VerticalAlign.TOP;const scroll=view.addComponent(ScrollView);scroll.content=content;scroll.horizontal=false;}
 notice(n:Notice){const a=this.a,msg=localized(n,a.game.s.locale),p=a.open(msg.title,700);this.body(p,msg.body);a.button(p,a.tr('action.confirm'),0,-285,360,48,()=>{void a.remote(async()=>{await a.operations.read(n.id);a.close();});},true);}
 notices(){const a=this.a,p=a.open(this.a.tr('live.0'),700);a.scroll(p,0,-20,400,530,(this.policy?.notices||[]).map(n=>({title:localized(n,a.game.s.locale).title,action:a.tr('action.details'),click:()=>this.notice(n)})));if(!this.policy?.notices.length)a.label(p,this.a.tr('live.1'),0,0,375,90,18);}
 updatePanel(){const a=this.a,p=a.open(this.a.tr('live.2'),540,false);this.blocked=true;a.label(p,this.a.tr('live.3')+'\n'+a.tr('ops.versionChange',{current:this.version,target:this.policy?.requiredVersion?.[this.platform]&&compareVersions(this.policy.requiredVersion[this.platform]!,'0')>0?this.policy.requiredVersion[this.platform]!:this.policy!.minimumVersion[this.platform]}),0,45,370,170,20);a.button(p,this.a.tr('live.4'),0,-100,360,48,()=>sys.openURL(this.policy!.storeUrls[this.platform]),true);a.button(p,this.a.tr('live.5'),0,-165,360,44,()=>void this.refresh());}
 inbox(confirmed=false){const a=this.a;void a.remote(async()=>{const mails=(await a.operations.inbox()).filter(m=>m.claimed===confirmed&&mailExpiry(m)>a.game.now()),p=a.open(a.tr('inbox.title'),700);[false,true].forEach((value,i)=>a.button(p,i?a.tr('live.12'):a.tr('live.13'),i?101:-101,247,190,44,()=>this.inbox(value),confirmed===value));a.scroll(p,0,-35,400,470,mails.map(m=>({title:localized(m,a.game.s.locale).title,sub:new Date(mailExpiry(m)).toLocaleString(a.game.s.locale),action:a.tr('action.details'),icon:9,art:'mail',click:()=>this.mail(m,confirmed)})));a.button(p,a.tr('extra.seasonRewards'),0,-303,370,36,()=>a.extensions.localInbox(confirmed));if(!mails.length)a.label(p,a.tr('live.14'),0,0,370,70,18);a.modalRefresh=()=>{if(mails.some(m=>mailExpiry(m)<=a.game.now()))this.inbox(confirmed);};});}
 mail(m:MailView,confirmed:boolean){const a=this.a,msg=localized(m,a.game.s.locale),p=a.open(msg.title,700),r=m.rewards;this.body(p,a.tr('ops.messageRewards',{body:msg.body,rewards:a.tr('ops.mailRewards',{gems:r.gems,shards:r.shards,dust:r.dust,petLevels:r.petLevels})}));a.button(p,a.tr(m.claimed?'extra.delete':'action.claim'),0,-285,360,48,()=>{if(m.claimed)a.confirm(a.tr('extra.delete'),a.tr('live.15'),()=>void a.remote(async()=>{await a.operations.delete(m.id);a.remoteBusy=false;this.inbox(true);}));else void a.remote(async()=>{await a.operations.claim(m.id);a.remoteBusy=false;this.inbox(true);});},true);a.modalRefresh=()=>{if(mailExpiry(m)<=a.game.now())this.inbox(confirmed);};}
 hub(){const a=this.a,p=a.open(this.a.tr('live.6'),620);const entries=[[this.a.tr('live.7'),()=>this.notices()],[a.tr('ops.inboxCount',{title:a.tr('inbox.title'),count:a.operations.mails.filter(m=>!m.claimed&&mailExpiry(m)>a.game.now()).length}),()=>this.inbox()],[a.tr('extra.notifications'),()=>this.notifications()],[this.a.tr('live.8'),()=>{void this.refresh().then(()=>{if(!this.blocked)a.info(this.a.tr('live.9'),a.tr('ops.currentVersion',{version:this.version,status:this.error?a.tr('online.unreachable'):a.tr('live.11')}));});}],[a.tr('consent.terms.title'),()=>a.entry.reviewDocument('terms')],[a.tr('consent.privacy.title'),()=>a.entry.reviewDocument('privacy')]] as [string,()=>void][];entries.forEach(([title,action],i)=>a.button(p,title,0,170-i*88,370,62,action));}
}
