import {sys,Mask,ScrollView,UITransform,Label} from 'cc';
import type {GameApp} from './GameApp';
import {APP_VERSION,Policy,Notice,Platform,validatePolicy,requiresUpdate,mailExpiry} from './core/LiveOps';
export class LiveOpsUI {
 policy:Policy|null=null; blocked=false; checking=false; elapsed=0; error=false;
 constructor(private a:GameApp){}
 text(ko:string,en:string){return this.a.game.s.locale==='ko'?ko:en;}
 get platform():Platform{return sys.os===sys.OS.ANDROID?'android':sys.os===sys.OS.IOS?'ios':'web';}
 async refresh(){if(this.checking||!this.a.onlineService.base)return;this.checking=true;try{this.policy=validatePolicy(await this.a.onlineService.request('/operations'));this.error=false;const blocked=requiresUpdate(this.policy,this.platform);if(blocked&&!this.blocked){this.a.close();this.updatePanel();}else if(!blocked&&this.blocked){this.blocked=false;this.a.close();}}catch{this.error=true;}finally{this.checking=false;}}
 tick(dt:number){this.elapsed+=dt;if(this.elapsed>=60){this.elapsed=0;void this.refresh();}if(!this.a.modal&&!this.blocked){const n=this.policy?.notices.find(n=>!this.a.game.s.claims.includes('notice.read.'+n.id));if(n)this.notice(n);}}
 body(p:any,body:string){const a=this.a,view=a.nodeAt(p,'message-scroll',0,5,380,420);view.addComponent(Mask);const h=Math.max(420,body.split('\n').reduce((sum,line)=>sum+Math.max(1,Math.ceil(line.length/22)),0)*27+30),content=a.nodeAt(view,'content',0,210,380,h);content.getComponent(UITransform)!.setAnchorPoint(.5,1);const label=a.label(content,body,0,-h/2,364,h,18);label.overflow=Label.Overflow.CLAMP;label.verticalAlign=Label.VerticalAlign.TOP;const scroll=view.addComponent(ScrollView);scroll.content=content;scroll.horizontal=false;}
 notice(n:Notice){const a=this.a,msg=n.localizations?.[a.game.s.locale]||n,p=a.open(msg.title,700);this.body(p,msg.body);a.button(p,a.tr('action.confirm'),0,-285,360,48,()=>{if(a.game.transaction(a.id('notice'),()=>{const key='notice.read.'+n.id;if(!a.game.s.claims.includes(key))a.game.s.claims.push(key);})){a.close();}else a.flushNotice();},true);}
 notices(){const a=this.a,p=a.open(this.a.tr('live.0'),700);a.scroll(p,0,-20,400,530,(this.policy?.notices||[]).map(n=>({title:(n.localizations?.[a.game.s.locale]||n).title,action:a.tr('action.details'),click:()=>this.notice(n)})));if(!this.policy?.notices.length)a.label(p,this.a.tr('live.1'),0,0,375,90,18);}
 updatePanel(){const a=this.a,p=a.open(this.a.tr('live.2'),540,false);this.blocked=true;a.label(p,this.a.tr('live.3')+'\n'+APP_VERSION+' → '+(this.policy?.requiredVersion?.[this.platform]||this.policy?.minimumVersion[this.platform]),0,45,370,170,20);a.button(p,this.a.tr('live.4'),0,-100,360,48,()=>sys.openURL(this.policy!.storeUrls[this.platform]),true);a.button(p,this.a.tr('live.5'),0,-165,360,44,()=>void this.refresh());}
 hub(){const a=this.a,p=a.open(this.a.tr('live.6'),620);const entries=[[this.a.tr('live.7'),()=>this.notices()],[a.tr('inbox.title')+' · '+a.game.s.extra.mails.filter(m=>!m.claimed&&mailExpiry(m)>a.game.now()).length,()=>a.extensions.inbox()],[a.tr('extra.notifications'),()=>a.extensions.notifications()],[this.a.tr('live.8'),()=>{void this.refresh().then(()=>{if(!this.blocked)a.info(this.a.tr('live.9'),this.a.tr('live.10')+APP_VERSION+'\n'+(this.error?a.tr('online.unreachable'):!a.onlineService.base?a.tr('online.unconfigured'):this.a.tr('live.11')));});}]] as [string,()=>void][];entries.forEach(([title,action],i)=>a.button(p,title,0,170-i*88,370,62,action));}
}
