import type { GameApp } from './GameApp';
import { Monetization, PRODUCTS, AD_PLACEMENTS, VIP_THRESHOLDS, AdPlacement, StoreQuote } from './core/Monetization';
export class MonetizationUI {
    quotes:StoreQuote[]=[];
    constructor(public a:GameApp,public model:Monetization){}
    tr(key:string,args:Record<string,string|number>={}){return this.a.tr(key,args);}
    price(id:string):string{const quote=this.quotes.find(q=>q.id===id);return quote?.price||'₩'+PRODUCTS.find(p=>p.id===id)!.krw.toLocaleString('ko-KR');}
    async run(work:()=>Promise<void>,offline=false):Promise<void>{const before=this.a.feedback.snapshot();this.a.feedback.asyncPending++;try{if(!offline||this.model.online.base)await this.model.online.connect(this.tr('online.defaultName'));await work();this.a.feedback.finish(before);}catch(e){const key=(e as Error).message;this.a.info(this.tr('money.result'),this.tr(/^(money|error|online)\./.test(key)?key:'money.verification'));}finally{this.a.feedback.asyncPending--;}}
    rows(){return PRODUCTS.filter(p=>p.kind==='consumable').map(p=>({title:this.tr(p.name,{count:p.gems}),sub:this.tr('money.packInfo',{count:p.gems}),action:this.price(p.id),click:()=>this.product(p.id),icon:4}));}
    store(){void this.run(async()=>{if(this.model.billing)this.quotes=await this.model.billing.catalog(PRODUCTS.map(p=>p.id));const status=this.model.online.base?await this.model.online.request('/commerce/status'):{tier:0,vipPoints:0};this.a.extensions.list('money.store',[
        {title:this.tr('money.balance',{count:this.a.game.s.gems}),sub:this.tr('money.priceRegion')},
        ...this.rows(),...PRODUCTS.filter(p=>p.kind!=='consumable').map(p=>({title:this.tr(p.name),sub:this.tr(p.configured?'money.passInfo':'money.bundleUnknown'),action:this.price(p.id),click:()=>this.product(p.id)})),
        {title:this.tr('money.vip'),sub:this.tr('money.vipStatus',{tier:status.tier,points:status.vipPoints}),action:this.tr('action.details'),click:()=>this.vip()},
        {title:this.tr('money.restore'),action:this.tr('action.apply'),click:()=>{void this.run(async()=>{await this.model.restore();this.result('money.restored');});}},
        {title:this.tr('money.retry'),action:this.tr('action.apply'),click:()=>{void this.run(async()=>{await this.model.retryPending();this.result('money.delivered');});}}
    ]);},true);}
    product(id:string){const product=PRODUCTS.find(p=>p.id===id)!;const p=this.a.open(this.tr(product.name,{count:product.gems}),580),quote=this.quotes.find(q=>q.id===id);this.a.label(p,this.price(id),0,165,370,60,34,'#ecc071');this.a.label(p,this.tr(product.kind==='consumable'?'money.packInfo':product.configured?'money.passInfo':'money.bundleUnknown',{count:product.gems}),0,70,370,110,20);this.a.label(p,this.tr(quote?'money.actualPrice':'money.priceRegion'),0,-40,370,75,15);this.a.button(p,this.tr('action.buy'),0,-140,370,55,()=>{if(!product.configured){this.result('money.bundleUnknown');return;}this.a.confirm(this.tr('money.confirm'),this.tr('money.confirmBody',{name:this.tr(product.name,{count:product.gems}),price:this.price(id)}),()=>{void this.run(async()=>{const state=await this.model.purchase(id);this.result('money.'+state);this.a.drawPanel();});});},true);this.a.button(p,this.tr('money.vip'),0,-220,370,42,()=>this.vip());}
    result(key:string){this.a.info(this.tr('money.result'),this.tr(key));this.a.updateHUD();}
    vip(){void this.run(async()=>{const s=await this.model.online.request('/commerce/status');this.a.extensions.list('money.vip',[{title:this.tr('money.vipStatus',{tier:s.tier,points:s.vipPoints}),sub:this.tr('money.vipPass',{time:s.passUntil>Date.now()?new Date(s.passUntil).toLocaleString(this.a.game.s.locale):this.tr('money.noPass')})},...VIP_THRESHOLDS.map((points,i)=>({points,i})).filter(v=>v.i===2||v.i===4).map(({points,i})=>({title:this.tr('money.vipTier',{tier:i+1,points}),sub:this.tr('money.vipBenefit.'+(i+1)),action:this.tr(s.tier>i?'action.selected':'error.locked')}))]);});}
    fairy(){const p=this.a.open(this.tr('money.fairy'),500);this.a.label(p,this.tr('money.fairyInfo'),0,120,370,130,20);this.a.button(p,this.tr('action.claim'),0,10,370,55,()=>this.a.act(()=>this.a.game.claimFairy(this.a.id('fairy')),()=>this.a.close()),true);this.a.button(p,this.tr('money.fairyBonus'),0,-75,370,55,()=>this.ads('fairy'));this.a.button(p,this.tr(this.a.game.s.extra.commerce.fairyAds?'money.adsOn':'money.adsOff'),0,-163,370,45,()=>{this.a.game.s.extra.commerce.fairyAds=!this.a.game.s.extra.commerce.fairyAds;this.a.game.persist();this.fairy();});}
    ads(group?:string){if(group==='fairy'&&!this.a.game.s.extra.commerce.fairyAds){this.result('money.disabled');return;}void this.run(async()=>{const s=this.model.online.base?await this.model.online.request('/commerce/status'):{placements:AD_PLACEMENTS.filter(p=>p.group!=='legacy').map(p=>({...p,used:0,skip:false,readyAt:0}))};this.a.extensions.list('money.adPoints',s.placements.filter((p:any)=>!group||p.group===group).map((p:any)=>({title:this.tr('money.ad.'+p.id),sub:this.tr('money.adReward.'+p.id),action:this.tr(p.limit&&p.used>=p.limit?'money.limitShort':p.skip?'action.claim':'money.watch'),click:()=>this.ad(p.id,p)})));},true);}
    ad(id:AdPlacement,status?:any){const p=this.a.open(this.tr('money.ad.'+id),550),rule=AD_PLACEMENTS.find(p=>p.id===id)!;this.a.label(p,this.tr('money.adReward.'+id),0,150,370,110,21);this.a.label(p,this.tr('money.adRule',{used:status?.used||0,limit:rule.limit||'∞',seconds:Math.max(0,Math.ceil(((status?.readyAt||0)-Date.now())/1000))}),0,35,370,80,17);this.a.label(p,this.tr('money.optIn'),0,-50,370,65,15);this.a.button(p,this.tr(status?.skip?'action.claim':'money.watch'),0,-146,370,55,()=>{if((id==='shop_chest'||id==='fairy_equipment')&&this.a.game.s.equipment.length>=100){this.result('error.full');return;}void this.run(async()=>{const result=await this.model.watch(id);this.result('money.adStatus.'+result);this.a.drawPanel();});},true);this.a.button(p,this.tr('action.cancel'),0,-218,370,43,()=>this.a.close());}
}
