import { randomBytes } from 'node:crypto';
import { Service, ServiceError } from './Service';
import { PRODUCTS, AD_PLACEMENTS, VIP_THRESHOLDS, CommerceGrant } from '../assets/scripts/core/Monetization';

/** Implement with store-side receipt verification and ad-provider SSV, never a client boolean. */
export interface CommerceVerifier {
    purchase(receipt:string):Promise<{transactionId:string;account:string;product:string;purchasedAt:number;vipPoints:number;revoked:boolean}>;
    ad(proof:string,ticket:string,account:string):Promise<{eventId:string;completed:boolean}>;
}
export class CommerceService {
    constructor(public service:Service,private verifier:CommerceVerifier|null=null){service.db.exec(`
      CREATE TABLE IF NOT EXISTS commerce_receipts(id TEXT PRIMARY KEY,account TEXT NOT NULL,product TEXT NOT NULL,created INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS commerce_grants(id TEXT PRIMARY KEY,account TEXT NOT NULL,payload TEXT NOT NULL,acked INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS commerce_accounts(account TEXT PRIMARY KEY,vip INTEGER NOT NULL DEFAULT 0,pass_until INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS ad_tickets(id TEXT PRIMARY KEY,account TEXT NOT NULL,placement TEXT NOT NULL,created INTEGER NOT NULL,completed INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS ad_events(id TEXT PRIMARY KEY,ticket TEXT NOT NULL UNIQUE);
    `);}
    profile(account:string):any{return this.service.one('SELECT vip,pass_until FROM commerce_accounts WHERE account=?',account)||{vip:0,pass_until:0};}
    status(account:string):any{const s=this.service,p=this.profile(account),tier=p.pass_until>s.now()?5:VIP_THRESHOLDS.filter(n=>p.vip>=n).length;return {connected:!!this.verifier,vipPoints:p.vip,passUntil:p.pass_until,tier,placements:AD_PLACEMENTS.filter(a=>a.group!=='legacy').map(a=>{const cycle=Math.floor(s.now()/a.period)*a.period,row=s.one('SELECT COUNT(*) AS n,MAX(created) AS last FROM ad_tickets WHERE account=? AND placement=? AND completed=1 AND created>=?',account,a.id,cycle);return {...a,used:row.n,readyAt:Math.max((s.one('SELECT MAX(created) AS last FROM ad_tickets WHERE account=? AND placement=? AND completed=1',account,a.id).last||0)+a.cooldown,a.group==='fairy'?(s.one("SELECT MAX(created) AS last FROM ad_tickets WHERE account=? AND placement LIKE 'fairy_%' AND completed=1",account).last||0)+120000:0),skip:tier>=(a.group==='fairy'?3:5)};})};}
    grants(account:string):CommerceGrant[]{return this.service.all('SELECT payload FROM commerce_grants WHERE account=? AND acked=0 ORDER BY rowid',account).map(r=>JSON.parse(r.payload));}
    grant(account:string,value:CommerceGrant):void{this.service.run('INSERT INTO commerce_grants(id,account,payload) VALUES(?,?,?)',value.id,account,JSON.stringify(value));}
    ack(account:string,id:unknown,key:unknown):any{return this.service.tx(account,key,()=>{const grant=this.service.one('SELECT account FROM commerce_grants WHERE id=?',this.service.text(id,1,100));if(!grant||grant.account!==account)throw new ServiceError(404,'online.notFound');this.service.run('UPDATE commerce_grants SET acked=1 WHERE id=?',id as string);return {acked:true};});}
    async purchase(account:string,receipt:unknown,key:unknown,expectedProduct?:unknown):Promise<any>{if(!this.verifier)throw new ServiceError(503,'money.storeUnavailable');const verified=await this.verifier.purchase(this.service.text(receipt,1,6000));const product=PRODUCTS.find(p=>p.id===verified.product);if(verified.account!==account||verified.revoked||!product?.configured||(expectedProduct!==undefined&&expectedProduct!==verified.product)||!Number.isInteger(verified.vipPoints)||verified.vipPoints<0||!Number.isFinite(verified.purchasedAt)||verified.purchasedAt>this.service.now())throw new ServiceError(400,'money.verification');this.service.text(verified.transactionId,1,120);return this.service.tx(account,key,()=>{const old=this.service.one('SELECT * FROM commerce_receipts WHERE id=?',verified.transactionId);if(old){if(old.account!==account||old.product!==product.id)throw new ServiceError(409,'money.verification');return {verified:true,duplicate:true};}const s=this.service,profile=this.profile(account),passUntil=product.kind==='season'?(Math.floor(verified.purchasedAt/(28*86400000))+1)*28*86400000:0,id=randomBytes(16).toString('hex');s.run('INSERT INTO commerce_receipts VALUES(?,?,?,?)',verified.transactionId,account,product.id,s.now());s.run('INSERT INTO commerce_accounts VALUES(?,?,?) ON CONFLICT(account) DO UPDATE SET vip=vip+excluded.vip,pass_until=MAX(pass_until,excluded.pass_until)',account,verified.vipPoints,passUntil);this.grant(account,{id,kind:'purchase',product:product.id,gems:product.gems,vipPoints:verified.vipPoints,passUntil:Math.max(profile.pass_until,passUntil)});return {verified:true,id};});}
    startAd(account:string,placement:unknown,key:unknown):any{return this.service.tx(account,key,()=>{const s=this.service,status=this.status(account),p=status.placements.find((p:any)=>p.id===placement);if(!p)throw new ServiceError(400,'error.invalid');if(!p.skip&&!this.verifier)throw new ServiceError(503,'money.adsUnavailable');if(p.limit&&p.used>=p.limit)throw new ServiceError(409,'money.limit');if(s.now()<p.readyAt)throw new ServiceError(409,'error.timer');const active=s.one('SELECT id FROM ad_tickets WHERE account=? AND placement=? AND completed=0 AND created>?',account,p.id,s.now()-600000);if(active&&!p.skip)return {id:active.id,skip:false};const id=randomBytes(16).toString('hex');s.run('INSERT INTO ad_tickets(id,account,placement,created) VALUES(?,?,?,?)',id,account,p.id,s.now());if(p.skip)this.finishAd(account,id);return {id,skip:p.skip};});}
    private finishAd(account:string,ticket:string):void{const s=this.service,row=s.one('SELECT * FROM ad_tickets WHERE id=? AND account=?',ticket,account);if(!row||row.completed)throw new ServiceError(409,'error.claimed');const p=this.status(account).placements.find((p:any)=>p.id===row.placement);if(p.limit&&p.used>=p.limit)throw new ServiceError(409,'money.limit');if(s.now()<p.readyAt)throw new ServiceError(409,'error.timer');s.run('UPDATE ad_tickets SET completed=1,created=? WHERE id=?',s.now(),ticket);this.grant(account,{id:ticket,kind:'ad',placement:row.placement,gems:row.placement==='fairy_diamond'?10:0,vipPoints:0,passUntil:0,...(row.placement==='fairy_gold_spree'?{goldSpreeUntil:s.now()+300000}:{}),...(row.placement==='fairy_damage_spree'?{damageSpreeUntil:s.now()+300000}:{}),...(row.placement==='mega_boost'?{boostUntil:s.now()+14400000}:{}),...(row.placement==='fairy_discount'?{discountUntil:s.now()+60000}:{})});}
    async completeAd(account:string,ticket:unknown,proof:unknown,key:unknown):Promise<any>{if(!this.verifier)throw new ServiceError(503,'money.adsUnavailable');const id=this.service.text(ticket,1,64),row=this.service.one('SELECT * FROM ad_tickets WHERE id=? AND account=?',id,account);if(!row||this.service.now()-row.created>600000)throw new ServiceError(409,'money.expired');const result=await this.verifier.ad(this.service.text(proof,1,6000),id,account);if(!result.completed)throw new ServiceError(400,'money.verification');this.service.text(result.eventId,1,120);return this.service.tx(account,key,()=>{if(this.service.now()-row.created>600000)throw new ServiceError(409,'money.expired');const prior=this.service.one('SELECT ticket FROM ad_events WHERE id=?',result.eventId);if(prior){if(prior.ticket!==id)throw new ServiceError(400,'money.verification');return {verified:true,duplicate:true};}this.finishAd(account,id);this.service.run('INSERT INTO ad_events VALUES(?,?)',result.eventId,id);return {verified:true};});}
}
