/** Stable identities: one distinct weapon/art/voice per saved hero slot. */
export const WEAPONS=['rifle','sniper','shotgun','pistols','revolver','smg','lmg','crossbow','bow','daggers','spear','axe','hammer','swordshield','katana','kusarigama','grenade','rocket','flamer','minigun','railgun','laser','plasma','gauntlets'] as const;
export type MercenaryWeapon=typeof WEAPONS[number];
export const ATTACK_SECONDS=[1.15,2.8,1.9,.45,1.4,.24,.32,2.1,1.55,.5,1.35,2.4,2.7,1.2,1.65,1.7,2.3,3.2,.2,.12,3,.16,2.5,.38] as const;
export function mercenaryArt(id:number){return Math.max(0,id)%24;}
export function mercenaryWeapon(id:number):MercenaryWeapon{return WEAPONS[mercenaryArt(id)];}
export function attackSeconds(id:number){return ATTACK_SECONDS[mercenaryArt(id)];}
export const MELEE:readonly MercenaryWeapon[]=['daggers','spear','axe','hammer','swordshield','katana','kusarigama','gauntlets'];
/** Every successful request advances quiet-period clock, even if suppressed. */
export class GrowthGate {
 private last=-Infinity;private until=-Infinity;
 request(now:number){const quiet=now-this.last>=1000;this.last=now;if(!quiet||now<this.until)return false;this.until=now+2000;return true;}
}
export function applyMercenaryText(t:Record<string,Record<string,string>>){
 const names=[['레아','블레어','루비','제트','스칼렛','네온','브릭','레이븐','실바','쉐이드','사라','프레야','아이언','발레리','츠키','카게','파이퍼','노바','신더','벌칸','제로','아이리스','아스트라','볼트'],['Rhea','Blair','Ruby','Jett','Scarlet','Neon','Brick','Raven','Sylva','Shade','Sara','Freya','Iron','Valerie','Tsuki','Kage','Piper','Nova','Cinder','Vulcan','Zero','Iris','Astra','Volt']];
 const weapons=[['돌격소총','저격총','펌프 산탄총','쌍권총','리볼버','기관단총','경기관총','석궁','장궁','쌍단검','장창','양손 도끼','전투 망치','검·방패','긴 카타나','사슬낫','유탄발사기','로켓발사기','화염방사기','미니건','레일건','레이저 캐논','플라즈마 런처','전격 건틀릿'],['Assault Rifle','Sniper Rifle','Pump Shotgun','Dual Pistols','Revolver','SMG','Light Machine Gun','Crossbow','Longbow','Twin Daggers','Spear','Battle Axe','War Hammer','Sword & Shield','Long Katana','Chain Sickle','Grenade Launcher','Rocket Launcher','Flamethrower','Minigun','Railgun','Laser Cannon','Plasma Launcher','Shock Gauntlets']];
 const intro=[['선두는 내가 맡을게!','한 발이면 충분해.','길 좀 비켜줄래?','둘 중 어느 총부터 볼래?','승부는 한 발로 끝내지.','시동 걸었어. 따라와!','내 뒤에 있어. 엄호할게.','발소리까지 숨겨.','바람이 길을 알려줄 거야.','벌써 네 뒤인데?','흔들리지 마. 길은 내가 연다.','하하! 오늘도 멋진 싸움이겠군!','벽이라면 부수면 그만.','이 방패 너머로는 못 지나간다.','칼을 뽑았다. 끝내겠다.','어디로 피할 생각이지?','계산은 끝! 귀 막아!','큰 문제엔 큰 한 방이지.','식기 전에 시작하자!','탄약? 충분히 가져왔지!','오차는 허용하지 않는다.','출력 안정. 전선을 지우겠어.','미지의 힘, 시험해 볼까?','한 판 붙자. 짜릿하게!'],['I will take point!','One shot is enough.','Mind clearing a path?','Which pistol first?','One round settles this.','Engine is hot. Keep up!','Stay behind me. Covering!','Hide even your footsteps.','The wind will guide us.','Already behind you.','Stand firm. I will lead.','Ha! A glorious fight awaits!','A wall? I can break it.','None shall pass this shield.','Blade drawn. It ends now.','Where will you run?','Math done! Cover your ears!','Big problem? Bigger rocket.','Let us turn up the heat!','Ammo? Brought plenty!','Zero margin for error.','Output stable. Clearing the front.','Time to test the unknown!','Come on. Feel the voltage!']];
 const growth=[['좋아, 더 빠르게!','조준은 더 정밀하게.','이제 더 묵직하겠는데?','한 박자 더 빠르게!','다음 승부가 기대되네.','속도를 더 올려볼까!','엄호는 나만 믿어.','더 멀리, 더 조용히.','화살에 바람을 실어.','눈 깜빡하면 놓쳐.','더 멀리 뻗는다!','힘이 솟는군!','다음 벽을 가져와.','더 단단하게 지켜주마.','한 치 더 날카롭게.','빈틈이 더 잘 보이는군.','폭발 반경 계산 완료!','이번엔 더 크게 간다!','온도가 올라간다!','아직 한참 더 쏠 수 있어!','관통력 보정 완료.','출력 상승. 안정적이야.','새 에너지, 확인 완료.','손끝까지 짜릿해!'],['Good. Faster now!','Aim refined.','That will hit harder.','One beat faster!','Ready for the next duel.','Let us speed things up!','Count on my covering fire.','Farther. Quieter.','Let the wind carry it.','Blink and you miss me.','My reach grows!','I feel the power!','Bring me the next wall.','I will hold the line.','An even keener edge.','Your openings are clear.','Blast calculations complete!','Going bigger this time!','Temperature rising!','Plenty more rounds to go!','Penetration calibrated.','Output up. Stable.','New energy confirmed.','Electric to my fingertips!']];
 ['ko','en'].forEach((locale,l)=>{
  for(let i=0;i<24;i++){t[locale]['hero.'+i]=names[l][i];t[locale]['hero.short.'+i]=names[l][i];t[locale]['merc.weapon.'+i]=weapons[l][i];t[locale]['merc.intro.'+i]=intro[l][i];t[locale]['merc.growth.'+i]=growth[l][i];}
 });
 Object.assign(t.ko,{'merc.unlocked':'새 용병 해금','merc.ready':'{name} · 합류 준비 완료','merc.cadence':'{weapon} · {seconds}초마다 공격','merc.statChange':'{before} → {after}','merc.level':'Lv.{before} → {after}','merc.captain':'좋아! 전선을 더 밀어붙이자!','merc.gallery':'용병 도감','merc.preview':'컷인 보기'});
 Object.assign(t.en,{'merc.unlocked':'MERCENARY UNLOCKED','merc.ready':'{name} · Ready to join','merc.cadence':'{weapon} · Attack every {seconds}s','merc.statChange':'{before} → {after}','merc.level':'Lv.{before} → {after}','merc.captain':'Good! Let us push the front!','merc.gallery':'Mercenary Roster','merc.preview':'View cut-in'});
}
