/** Presentation-only theme: save keys and economy retain their existing identities. */
export function applyMilitaryTheme(t:Record<string,Record<string,string>>):void {
 const terms:Record<string,[string,string][]>= {
  ko:[['잿불의 탑','여군 키우기'],['능선 수호자','돌격대장'],['잿불 수호자','돌격대장'],['수호자','대장'],['용사','대원'],['동료','분대원'],['정령','지원 드론'],['유물','작전 기록'],['주문','전술'],['마나','전술 에너지'],['환생','재배치'],['원정','작전'],['탑','전선'],['검술','사격'],['검 공격','소총 공격'],['요정','보급 드론'],['부화','조립'],['알 획득','부품 획득'],['길드','연대'],['마법','전술'],['신비','기밀'],['골드','군자금'],['능선검사 로웬','소총수 레아'],['검을','총기를'],['검:','소총:'],['두루마리','훈련 교범'],['소환','지원'],['비전','전자전'],['연금','군수'],['오라','통신기'],['투구','전술 헬멧'],['몬스터','적 병력'],['잿빛 능선','전방 기지'],['잿불 축제','특별 작전'],['여우 아이콘','드론 아이콘'],['첫 알','첫 조립 캡슐']],
  en:[['Ember Guardian','Squad Captain'],['Ridge Guardian','Squad Captain'],['Guardian','Captain'],['guardian','captain'],['Hero','Soldier'],['hero','soldier'],['Spirit','Drone'],['spirit','drone'],['Pet','Drone'],['pet','drone'],['Artifact','Intel'],['artifact','intel'],['Spell','Tactic'],['spell','tactic'],['Mana','Energy'],['mana','energy'],['Prestige','Redeploy'],['prestige','redeploy'],['Expedition','Operation'],['expedition','operation'],['Fairy','Supply drone'],['fairy','supply drone'],['Hatch','Assemble'],['hatch','assemble'],['Guild','Regiment'],['guild','regiment'],['Gold','Funds'],['blade','rifle'],['Blade','Rifle'],['scrolls','manuals'],['Arcane','Electronic Warfare'],['Alchemy','Logistics'],['Summon','Support'],['Aura','Radio'],['Sword','Rifle'],['Helm','Helmet']]
 };
 for(const locale of ['ko','en'])for(const key of Object.keys(t[locale])){
  if(/^(consent\.|ops\.privacy|ops\.terms)/.test(key))continue;
  t[locale][key]=t[locale][key].split(/(\{[^}]+\})/g).map(part=>{if(part.startsWith('{'))return part;for(const [from,to]of terms[locale])part=part.split(from).join(to);return part;}).join('');
 }
 Object.assign(t.ko,{'game.name':'여군 키우기','entry.subtitle':'강철 전선 · 그녀들의 반격','entry.titleHint':'대장을 육성하고 정예 분대와 전선을 돌파하세요.','nav.master':'대장','nav.heroes':'분대','nav.pets':'드론','nav.equipment':'무장','nav.artifacts':'작전 기록','nav.shop':'보급소','action.mana':'전술 에너지','master.title':'돌격대장','art.enemy.golem':'중장갑 전차','art.enemy.forest-wolf':'적 돌격병','art.enemy.spectral-knight':'적 특수부대','art.enemy.flame-spirit':'전투 드론','art.enemy.skeleton':'적 소총병','art.enemy.tree-boss':'공성 전차','art.enemy.ice-boss':'장갑 지휘차','art.enemy.crystal-boss':'강습 전차','spell.0':'정밀 사격','spell.1':'전투 자극제','spell.2':'지원 사격','spell.3':'철갑탄','spell.4':'집중 포화','spell.5':'공중 지원'});
 Object.assign(t.en,{'game.name':'ARMY GIRL','entry.subtitle':'Steel Front · Strike Back','entry.titleHint':'Train your captain. Recruit an elite squad. Break the front.','nav.master':'Captain','nav.heroes':'Squad','nav.pets':'Drones','nav.equipment':'Arsenal','nav.artifacts':'Intel','nav.shop':'Supply','action.mana':'Energy','master.title':'Squad Captain','art.enemy.golem':'Heavy Tank','art.enemy.forest-wolf':'Assault Trooper','art.enemy.spectral-knight':'Special Forces','art.enemy.flame-spirit':'Combat Drone','art.enemy.skeleton':'Enemy Rifleman','art.enemy.tree-boss':'Siege Tank','art.enemy.ice-boss':'Command Armor','art.enemy.crystal-boss':'Assault Tank','spell.0':'Precision Shot','spell.1':'Combat Stim','spell.2':'Support Fire','spell.3':'Armor Piercing','spell.4':'Suppressive Fire','spell.5':'Air Support'});
 const slots=[['소총','전술 헬멧','방탄복','통신기','계급장'],['Rifle','Helmet','Body Armor','Radio','Insignia']];
 for(let i=0;i<5;i++){t.ko['slot.'+i]=slots[0][i];t.en['slot.'+i]=slots[1][i];}
 for(let i=0;i<12;i++){t.ko['pet.'+i]=['정찰','공격','보급'][i%3]+' 드론 Mk.'+(Math.floor(i/3)+1);t.en['pet.'+i]=['Scout','Attack','Supply'][i%3]+' Drone Mk.'+(Math.floor(i/3)+1);}
 for(let i=0;i<30;i++){t.ko['artifact.'+i]=['기밀 작전 보고서','전술 교범','정찰 데이터','보급 협약','전자전 기록'][i%5]+' '+(Math.floor(i/5)+1);t.en['artifact.'+i]=['Classified Report','Field Manual','Recon Data','Supply Protocol','Electronic Warfare Log'][i%5]+' '+(Math.floor(i/5)+1);}
 for(let i=0;i<40;i++){for(const locale of ['ko','en'])for(const prefix of ['hero.short.','hero.'])if(t[locale][prefix+i])t[locale][prefix+i]=(locale==='ko'?['레아','블레어','카밀라']:['Rhea','Blair','Camilla'])[i%3]+(i>=3?' '+(Math.floor(i/3)+1):'');}
}
